/**
 * Report Configuration
 * Defines the structure, sections, and data sources for KVK reports
 */

const reportConfig = {
    metadata: {
        name: 'KVK Comprehensive Report',
        version: '1.0.0',
        description: 'Comprehensive report containing all modules for KVK',
    },
    pdfFooter: {
        enabled: true,
        textTemplate: 'Page {current} of {total}',
        fontSize: 9,
        color: { r: 90, g: 90, b: 90 },
        bottomMarginPt: 24,
        align: 'right',
        fontName: 'Helvetica',
    },

    sections: [
        {
            id: '1.1',
            title: 'KVK Basic Information',
            description: 'Basic details about the KVK including contact information and geographic data',
            subsection: true,
            parentSectionId: '1',
            dataSource: 'kvk',
            format: 'custom',                 
            customTemplate: 'about-kvk-view', // temp;ate key
            filters: {
                dateFields: [],
            },
            fields: [
                { dbField: 'kvkName', displayName: 'KVK Name' },
                { dbField: 'address', displayName: 'Address' },
                { dbField: 'email', displayName: 'Email' },
                { dbField: 'mobile', displayName: 'Mobile' },
                { dbField: 'landline', displayName: 'Office Phone', optional: true },
                { dbField: 'fax', displayName: 'Fax', optional: true },
                { dbField: 'zone.zoneName', displayName: 'Zone' },
                { dbField: 'state.stateName', displayName: 'State' },
                { dbField: 'district.districtName', displayName: 'District' },
                { dbField: 'org.orgName', displayName: 'Organization' },
                { dbField: 'university.universityName', displayName: 'University', optional: true },
                { dbField: 'hostOrg', displayName: 'Host Organization' },
                { dbField: 'hostAddress', displayName: 'Host Address', optional: true },
                { dbField: 'hostLandline', displayName: 'Host Office Phone', optional: true },
                { dbField: 'hostFax', displayName: 'Host Fax', optional: true },
                { dbField: 'hostEmail', displayName: 'Host Email', optional: true },
                { dbField: 'yearOfSanction', displayName: 'Year of Sanction' },
                { dbField: 'landDetails', displayName: 'Land Details', type: 'raw', optional: true },
            ],
        },
        {
            id: '1.2',
            title: 'Bank Account Details',
            description: 'All bank accounts associated with the KVK',
            subsection: true,
            parentSectionId: '1',
            dataSource: 'kvkBankAccounts',
            format: 'custom',
            customTemplate: 'about-kvk-bank-accounts',
            filters: {
                dateFields: ['createdAt'],
            },
            // Column order mirrors the sample: KVK Name, Account Type, Account Name, Name of the bank, Location, Account Number
            fields: [
                { dbField: 'kvk.kvkName', displayName: 'KVK Name' },
                { dbField: 'accountType', displayName: 'Account Type' },
                { dbField: 'accountName', displayName: 'Account Name' },
                { dbField: 'bankName', displayName: 'Name of the bank' },
                { dbField: 'location', displayName: 'Location' },
                { dbField: 'accountNumber', displayName: 'Account Number' },
            ],
        },
        {
            id: '1.3',
            title: 'Employee Details',
            description: 'Heads of KVKs (position order = 1)',
            subsection: true,
            parentSectionId: '1',
            dataSource: 'kvkEmployeesHeads',
            format: 'custom',
            customTemplate: 'about-kvk-employee-contacts',
            filters: {
                dateFields: ['createdAt'],
            },
            fields: [
                { dbField: 'kvk.kvkName', displayName: 'KVK' },
                { dbField: 'staffName', displayName: 'Name' },
                { dbField: 'residence', displayName: 'Residence', optional: true },
                { dbField: 'mobile', displayName: 'Mobile' },
                { dbField: 'email', displayName: 'Email' },
            ],
        },
        {
            id: '1.4',
            title: 'All KVK staff Details',
            description: 'All active employees/staff of the KVK',
            subsection: true,
            parentSectionId: '1',
            dataSource: 'kvkEmployees',
            format: 'custom',
            customTemplate: 'about-kvk-employees-full',
            filters: {
                dateFields: ['createdAt'],
            },
            fields: [
                { dbField: 'kvk.kvkName', displayName: 'KVK' },
                { dbField: 'sanctionedPost.postName', displayName: 'Sanctioned post' },
                { dbField: 'staffName', displayName: 'Name of the Incumbent' },
                { dbField: 'dateOfBirth', displayName: 'Date of Birth', type: 'date' },
                { dbField: 'discipline.disciplineName', displayName: 'Discipline' },
                { dbField: 'payLevel.levelName', displayName: 'Pay Scale with Present Basic', optional: true },
                { dbField: 'dateOfJoining', displayName: 'Date of joining', type: 'date' },
                { dbField: 'staffCategory.categoryName', displayName: 'Category (SC/ST/ OBC/ General)', optional: true },
            ],
        },  
        {
            id: '1.5',
            title: 'Infrastructure Details',
            description: 'All infrastructure records for the KVK',
            subsection: true,
            parentSectionId: '1',
            dataSource: 'kvkInfrastructure',
            format: 'table',
            filters: {
                dateFields: ['createdAt'],
            },
            fields: [
                { dbField: 'infraMaster.name', displayName: 'Infrastructure Name' },
                { dbField: 'notYetStarted', displayName: 'Not Yet Started', type: 'boolean' },
                { dbField: 'completedPlinthLevel', displayName: 'Completed Plinth Level', type: 'boolean' },
                { dbField: 'completedLintelLevel', displayName: 'Completed Lintel Level', type: 'boolean' },
                { dbField: 'completedRoofLevel', displayName: 'Completed Roof Level', type: 'boolean' },
                { dbField: 'totallyCompleted', displayName: 'Totally Completed', type: 'boolean' },
                { dbField: 'plinthAreaSqM', displayName: 'Plinth Area (sq m)' },
                { dbField: 'underUse', displayName: 'Under Use', type: 'boolean' },
                { dbField: 'sourceOfFunding', displayName: 'Source of Funding' },
            ],
        },
        {
            id: '1.6',
            title: 'Vehicle Details',
            description: 'All vehicles and their maintenance records',
            subsection: true,
            parentSectionId: '1',
            dataSource: 'kvkVehicles',
            format: 'custom',
            customTemplate: 'about-kvk-vehicles',
            filters: {
                dateFields: ['createdAt'],
            },
            fields: [
                { dbField: 'kvk.kvkName', displayName: 'KVK' },
                { dbField: 'vehicleName', displayName: 'Type of vehicle' },
                { dbField: 'yearOfPurchase', displayName: 'Year of purchase' },
                { dbField: 'totalCost', displayName: 'Cost (Rs.)' },
                { dbField: 'totalRun', displayName: 'Total Run(km/hrs)', optional: true },
                { dbField: 'presentStatus', displayName: 'Present status' },
            ],
        },
        {
            id: '1.7',
            title: 'Equipment Details',
            description: 'All equipments and their details',
            subsection: true,
            parentSectionId: '1',
            dataSource: 'kvkEquipments',
            format: 'grouped-table',
            filters: {
                dateFields: ['createdAt'],
            },
            fields: [
                { dbField: 'equipmentName', displayName: 'Equipment Name' },
                { dbField: 'yearOfPurchase', displayName: 'Year of Purchase' },
                { dbField: 'totalCost', displayName: 'Total Cost', type: 'currency' },
                { dbField: 'presentStatus', displayName: 'Present Status' },
                { dbField: 'sourceOfFunding', displayName: 'Source of Funding' },
                { dbField: 'reportingYear', displayName: 'Reporting Year', optional: true },
            ],
        },
        {
            id: '1.8',
            title: 'Farm Implement Details',
            description: 'All farm implements',
            subsection: true,
            parentSectionId: '1',
            dataSource: 'kvkFarmImplements',
            format: 'table',
            filters: {
                dateFields: ['createdAt'],
            },
            fields: [
                { dbField: 'implementName', displayName: 'Implement Name' },
                { dbField: 'yearOfPurchase', displayName: 'Year of Purchase' },
                { dbField: 'totalCost', displayName: 'Total Cost', type: 'currency' },
                { dbField: 'presentStatus', displayName: 'Present Status' },
                { dbField: 'sourceOfFund', displayName: 'Source of Fund' },
            ],
        },
        {
            id: '1.9',
            title: 'Vehicles Records',
            description: 'Vehicle reporting-year records (Vehicle Details form)',
            subsection: true,
            parentSectionId: '1',
            dataSource: 'kvkVehicleDetails',
            format: 'custom',
            customTemplate: 'about-kvk-vehicle-details',
            filters: {
                dateFields: ['createdAt'],
            },
            fields: [
                { dbField: 'reportingYear', displayName: 'Year' },
                { dbField: 'kvk.kvkName', displayName: 'KVK' },
                { dbField: 'vehicleName', displayName: 'Vehicle' },
                { dbField: 'registrationNo', displayName: 'Registration No.' },
                { dbField: 'yearOfPurchase', displayName: 'Year of purchase' },
                { dbField: 'totalCost', displayName: 'Cost (Rs.)' },
                { dbField: 'totalRun', displayName: 'Total Run(km/hrs)' },
                { dbField: 'presentStatus', displayName: 'Present status' },
                { dbField: 'repairingCost', displayName: 'Repairing Cost', optional: true },
                { dbField: 'sourceOfFunding', displayName: 'Funding Source', optional: true },
            ],
        },
        {
            id: '1.11',
            title: 'Equipment Records',
            description: 'Equipment reporting-year records (Equipment Details form)',
            subsection: true,
            parentSectionId: '1',
            dataSource: 'kvkEquipmentRecords',
            format: 'custom',
            customTemplate: 'about-kvk-equipment-records',
            filters: {
                dateFields: ['createdAt'],
            },
            fields: [
                { dbField: 'reportingYear', displayName: 'Year' },
                { dbField: 'kvk.kvkName', displayName: 'KVK' },
                { dbField: 'equipmentName', displayName: 'Equipment Name' },
                { dbField: 'yearOfPurchase', displayName: 'Year of purchase' },
                { dbField: 'totalCost', displayName: 'Cost (Rs.)' },
                { dbField: 'sourceOfFunding', displayName: 'Source of fund' },
                { dbField: 'presentStatus', displayName: 'Present status' },
            ],
        },
        // ── OFT (On-Farm Testing) ───────────────────────────────────
        {
            id: '2.1',
            title: 'OFT Summary',
            description: 'Technology Assessed by KVK - sector-wise thematic area summary',
            subsection: true,
            parentSectionId: '2',
            dataSource: 'oftSummary',
            format: 'custom',
            customTemplate: 'oft-summary',
            filters: {
                dateFields: ['createdAt'],
            },
            fields: [],
        },
        {
            id: '2.2',
            title: 'OFT Details',
            description: 'Individual OFT trial detail cards with results',
            subsection: true,
            parentSectionId: '2',
            dataSource: 'oftDetailCards',
            format: 'custom',
            customTemplate: 'oft-detail-cards',
            filters: {
                dateFields: ['createdAt'],
            },
            fields: [],
        },
        {
            id: '2.8.1',
            title: 'Performance of Demonstration under CFLD',
            description: 'Combined CFLD report with technical, economic, socio-economic and perception parameters',
            subsection: true,
            parentSectionId: '3',
            dataSource: 'cfldCombined',
            format: 'custom',
            customTemplate: 'cfld-combined',
            filters: {
                dateFields: ['createdAt'],
                yearFields: ['reportingYear'],
            },
            fields: [
                { dbField: 'reportingYear', displayName: 'Reporting Year', type: 'date' },
                { dbField: 'kvkName', displayName: 'KVK Name' },
                { dbField: 'stateName', displayName: 'State' },
                { dbField: 'cropTypeName', displayName: 'Crop Type' },
                { dbField: 'seasonName', displayName: 'Season' },
                { dbField: 'cropName', displayName: 'Crop' },
                { dbField: 'areaInHa', displayName: 'Area (ha)' },
                { dbField: 'technologyDemonstrated', displayName: 'Detail of technology demonstrated' },
                { dbField: 'farmerYield', displayName: 'Yield in farmer field (q/ha)' },
                { dbField: 'demoYieldAvg', displayName: 'Yield in demonstration (q/ha)' },
                { dbField: 'percentIncrease', displayName: '% Increase' },
            ],
        },
        {
            id: '2.8.2',
            title: 'Extension activities under CFLD conducted',
            description: 'CFLD extension activities with participant category counts',
            subsection: true,
            parentSectionId: '3',
            dataSource: 'cfldExtensionActivity',
            format: 'custom',
            customTemplate: 'cfld-extension-activity',
            filters: {
                dateFields: ['activityDate'],
            },
            fields: [
                { dbField: 'kvkName', displayName: 'KVK Name' },
                { dbField: 'extensionActivityName', displayName: 'Extension Activities organized' },
                { dbField: 'activityDate', displayName: 'Activity Date', type: 'date' },
                { dbField: 'placeOfActivity', displayName: 'Place of Activity' },
                { dbField: 'generalM', displayName: 'General M' },
                { dbField: 'generalF', displayName: 'General F' },
                { dbField: 'obcM', displayName: 'OBC M' },
                { dbField: 'obcF', displayName: 'OBC F' },
                { dbField: 'scM', displayName: 'SC M' },
                { dbField: 'scF', displayName: 'SC F' },
                { dbField: 'stM', displayName: 'ST M' },
                { dbField: 'stF', displayName: 'ST F' },
                { dbField: 'totalFarmers', displayName: 'Total Farmers' },
            ],
        },
        {
            id: '2.8.3',
            title: 'Details of budget utilization',
            description: 'CFLD crop-wise budget utilization details',
            subsection: true,
            parentSectionId: '3',
            dataSource: 'cfldBudgetUtilization',
            format: 'custom',
            customTemplate: 'cfld-budget-utilization',
            filters: {
                dateFields: ['createdAt'],
                yearFields: ['reportingYearDate'],
            },
            fields: [
                { dbField: 'kvkName', displayName: 'KVK Name' },
                { dbField: 'seasonName', displayName: 'Season' },
                { dbField: 'cropName', displayName: 'Crop' },
                { dbField: 'overallFundAllocation', displayName: 'Overall fund allocation' },
                { dbField: 'areaAllotted', displayName: 'Area (ha) alloted' },
                { dbField: 'areaAchieved', displayName: 'Area (ha) achieved' },
            ],
        },
        {
            id: '2.9',
            title: 'CRA Details',
            description: 'Climate resilient agriculture details with state-wise presentation',
            subsection: true,
            parentSectionId: '3',
            dataSource: 'craDetails',
            format: 'custom',
            customTemplate: 'cra-details-state-wise',
            filters: {
                dateFields: [],
                yearFields: ['reportingYear'],
            },
            fields: [],
        },
        {
            id: '2.10',
            title: 'CRA Extension Activity',
            description: 'Extension activities under climate resilient agriculture',
            subsection: true,
            parentSectionId: '3',
            dataSource: 'craExtensionActivity',
            format: 'custom',
            customTemplate: 'cra-extension-activity',
            filters: {
                dateFields: ['startDate'],
            },
            fields: [],
        },
        {
            id: '2.11',
            title: 'Formation and Promotion of FPOs as CBBOs under NCDC Funding',
            description: 'FPO registration, training and business performance under CBBO support',
            subsection: true,
            parentSectionId: '3',
            dataSource: 'fpoCbboDetails',
            format: 'custom',
            customTemplate: 'fpo-cbbo-details',
            filters: {
                dateFields: ['reportingYear'],
            },
            fields: [],
        },
        {
            id: '2.12',
            title: 'Details of commodity-based organizations/Farmers Cooperative Society/FPO Formed/Associated with KVK under NCDC Funding',
            description: 'FPO management profile details under NCDC funding',
            subsection: true,
            parentSectionId: '3',
            dataSource: 'fpoManagement',
            format: 'custom',
            customTemplate: 'fpo-management-details',
            filters: {
                dateFields: ['reportingYear'],
            },
            fields: [],
        },
        {
            id: '2.13',
            title: 'DRMR Details',
            description: 'DRMR varietal and economics comparison details',
            subsection: true,
            parentSectionId: '3',
            dataSource: 'drmrDetails',
            format: 'custom',
            customTemplate: 'drmr-details',
            filters: {
                dateFields: ['reportingYear'],
            },
            fields: [],
        },
        {
            id: '2.14',
            title: 'DRMR Activity',
            description: 'Details augmenting rapeseed-mustard production activities with participant category totals',
            subsection: true,
            parentSectionId: '3',
            dataSource: 'drmrActivity',
            format: 'custom',
            customTemplate: 'drmr-activity',
            filters: {
                dateFields: ['reportingYear', 'startDate', 'endDate'],
                yearFields: ['reportingYear'],
            },
            fields: [],
        },
        {
            id: '2.15',
            title: 'NARI Nutrition Garden Details',
            description: 'Details of established nutrition garden in nutri-smart village',
            subsection: true,
            parentSectionId: '3',
            dataSource: 'nariNutritionGarden',
            format: 'custom',
            customTemplate: 'nari-nutrition-garden',
            filters: {
                dateFields: ['reportingYear'],
            },
            fields: [],
        },
        {
            id: '2.16',
            title: 'NARI Bio-fortified Crops',
            description: 'Details of bio-fortified crops used in nutri-smart village with beneficiary category counts',
            subsection: true,
            parentSectionId: '3',
            dataSource: 'nariBioFortified',
            format: 'custom',
            customTemplate: 'nari-bio-fortified',
            filters: {
                dateFields: ['reportingYear'],
                yearFields: ['reportingYear'],
            },
            fields: [],
        },
        {
            id: '2.17',
            title: 'NARI Value Addition',
            description: 'Details of value addition in nutri-smart village with beneficiary category counts',
            subsection: true,
            parentSectionId: '3',
            dataSource: 'nariValueAddition',
            format: 'custom',
            customTemplate: 'nari-value-addition',
            filters: {
                dateFields: ['reportingYear'],
                yearFields: ['reportingYear'],
            },
            fields: [],
        },
        {
            id: '2.18',
            title: 'NARI Training Programmes',
            description: 'Training programmes in nutri-smart village with participant category counts',
            subsection: true,
            parentSectionId: '3',
            dataSource: 'nariTraining',
            format: 'custom',
            customTemplate: 'nari-training',
            filters: {
                dateFields: ['reportingYear'],
                yearFields: ['reportingYear'],
            },
            fields: [],
        },
        {
            id: '2.19',
            title: 'NARI Extension Activities',
            description: 'Extension activities under NARI project with beneficiary category counts',
            subsection: true,
            parentSectionId: '3',
            dataSource: 'nariExtension',
            format: 'custom',
            customTemplate: 'nari-extension',
            filters: {
                dateFields: ['reportingYear'],
                yearFields: ['reportingYear'],
            },
            fields: [],
        },
        {
            id: '2.20',
            title: 'ARYA Current Year Details',
            description: 'Attracting and retaining youth in agriculture (current year)',
            subsection: true,
            parentSectionId: '3',
            dataSource: 'aryaCurrent',
            format: 'custom',
            customTemplate: 'arya-current',
            filters: {
                dateFields: ['reportingYear'],
                yearFields: ['reportingYear'],
            },
            fields: [],
        },
        {
            id: '2.21',
            title: 'ARYA Previous Year Details',
            description: 'Attracting and retaining youth in agriculture (previous year evaluation)',
            subsection: true,
            parentSectionId: '3',
            dataSource: 'aryaPrevYear',
            format: 'custom',
            customTemplate: 'arya-prev-year',
            filters: {
                dateFields: ['reportingYear'],
                yearFields: ['reportingYear'],
            },
            fields: [],
        },
        {
            id: '2.22',
            title: 'CSISA Details',
            description: 'Details of Cereal Systems Initiative for South Asia (CSISA) with crop trial data',
            subsection: true,
            parentSectionId: '3',
            dataSource: 'csisa',
            format: 'custom',
            customTemplate: 'csisa',
            filters: {
                dateFields: ['reportingYear'],
                yearFields: ['reportingYear'],
            },
            fields: [],
        },
        {
<<<<<<< Updated upstream
            id: '2.23',
            title: 'TSP / SCSP Details',
            description: 'Details of Tribal Sub Plan (TSP) and Scheduled Caste Sub Plan (SCSP)',
            subsection: true,
            parentSectionId: '3',
            dataSource: 'tspScsp',
            format: 'custom',
            customTemplate: 'tsp-scsp',
            filters: {
                dateFields: ['reportingYear'],
                yearFields: ['reportingYear'],
            },
            fields: [],
        },
        {
            id: '2.24.1',
            title: 'NICRA – Basic Information (District and Adopted Village)',
            description: 'Rainfall, temperature, dry spells, intensive rain, flood water depth/duration',
            subsection: true,
            parentSectionId: '3',
            dataSource: 'nicraBasic',
            format: 'custom',
            customTemplate: 'nicra-basic',
            filters: {
                dateFields: ['reportingDate', 'startDate'],
                yearFields: ['reportingDate', 'startDate'],
            },
            fields: [],
        },
        {
            id: '2.24.2',
            title: 'NICRA – Training',
            description: 'Training courses with duration, type, and participant categories',
            subsection: true,
            parentSectionId: '3',
            dataSource: 'nicraTraining',
            format: 'custom',
            customTemplate: 'nicra-training',
            filters: {
                dateFields: ['startDate', 'endDate'],
                yearFields: ['startDate', 'endDate'],
            },
            fields: [],
        },
        {
            id: '2.24',
            title: 'Seed Hub Programme – Seed Production and Sale',
            description: 'Information of quality seed produced in participatory mode under Seed Hub',
            subsection: true,
            parentSectionId: '3',
            dataSource: 'seedHub',
            format: 'custom',
            customTemplate: 'seed-hub',
            filters: {
                dateFields: ['reportingYear'],
                yearFields: ['reportingYear'],
            },
            fields: [],
        },
        {
            id: '2.25',
            title: 'Other Programmes organized by KVK (not covered above)',
            description: 'Other programmes with beneficiary categories and KVK name column',
            subsection: true,
            parentSectionId: '3',
            dataSource: 'otherProgrammes',
            format: 'custom',
            customTemplate: 'other-programmes',
            filters: {
                dateFields: ['programmeDate'],
                yearFields: ['programmeDate'],
            },
            fields: [],
=======
            id: '10.20',
            title: 'Special Programmes',
            description: 'List of Special Programmes Undertaken by the KVK',
            subsection: true,
            parentSectionId: '10',
            dataSource: 'specialProgramme',
            format: 'custom',
            customTemplate: 'special-programme',
            filters: {
                dateFields: ['initiationDate'],
                yearFields: ['reportingYear'],
            },
            fields: [
                { dbField: 'programmeType', displayName: 'Programme Type' },
                { dbField: 'programmeName', displayName: 'Name of the Programme/Scheme' },
                { dbField: 'programmePurpose', displayName: 'Purpose of programme' },
                { dbField: 'initiationDate', displayName: 'Date/Month of initiation', type: 'date' },
                { dbField: 'fundingAgency', displayName: 'Funding agency' },
                { dbField: 'amount', displayName: 'Amount(Rs.)', type: 'currency' },
            ],
        },
        {
            id: '2.14',
            title: 'Functional Linkage',
            description: 'Functional Linkage with Different Organisations',
            subsection: true,
            parentSectionId: '2',
            dataSource: 'functionalLinkage',
            format: 'custom',
            customTemplate: 'functional-linkage',
            filters: {
                dateFields: ['createdAt'],
                yearFields: ['reportingYear'],
            },
            fields: [
                { dbField: 'organizationName', displayName: 'Name of Organization' },
                { dbField: 'natureOfLinkage', displayName: 'Nature of Linkage' },
            ],
        },
        {
            id: '10.3',
            title: 'Success Stories',
            description: 'Success stories and Case studies of farmers/entrepreneurs',
            subsection: true,
            parentSectionId: '10',
            dataSource: 'successStory',
            format: 'custom',
            customTemplate: 'success-story',
            filters: {
                dateFields: ['createdAt'],
                yearFields: ['reportingYear'],
            },
            fields: [
                { dbField: 'farmerName', displayName: 'Name of the farmer/ entrepreneur' },
                { dbField: 'storyTitle', displayName: 'Title of the success story/case study' },
                { dbField: 'enterprise', displayName: 'Enterprise' },
                { dbField: 'netIncome', displayName: 'Net income', type: 'currency' },
            ],
        },
        {
            id: '10.2',
            title: 'Entrepreneurship',
            description: 'Details of entrepreneurship/startup developed by KVK',
            subsection: true,
            parentSectionId: '10',
            dataSource: 'entrepreneurship',
            format: 'custom',
            customTemplate: 'entrepreneurship',
            filters: {
                dateFields: ['createdAt'],
                yearFields: ['reportingYear'],
            },
            fields: [
                { dbField: 'entrepreneurName', displayName: 'Name of the entrepreneur' },
                { dbField: 'enterpriseType', displayName: 'Type of Enterprise' },
                { dbField: 'annualIncome', displayName: 'Annual Income', type: 'currency' },
                { dbField: 'yearOfEstablishment', displayName: 'Year of establishment' },
            ],
        },
        {
            id: '10.1',
            title: 'Impact of KVK activities',
            description: 'Impact of KVK activities/ large-scale adoption of technology',
            subsection: true,
            parentSectionId: '10',
            dataSource: 'kvkImpactActivity',
            format: 'custom',
            customTemplate: 'kvk-impact-activity',
            filters: {
                dateFields: ['createdAt'],
                yearFields: ['reportingYear'],
            },
            fields: [
                { dbField: 'specificArea', displayName: 'Specific Area' },
                { dbField: 'farmersBenefitted', displayName: 'Farmers Benefitted' },
                { dbField: 'adoptionPercentage', displayName: '% Adoption' },
            ],
        },
        {
            id: '10.8',
            title: 'Demonstration Units',
            description: 'Performance of Demonstration Units (Other than Instructional Farm)',
            subsection: true,
            parentSectionId: '10',
            dataSource: 'demonstrationUnit',
            format: 'custom',
            customTemplate: 'demonstration-unit',
            filters: {
                dateFields: ['createdAt'],
                yearFields: ['reportingYear'],
            },
            fields: [
                { dbField: 'demoUnitName', displayName: 'Name of Demo Unit' },
                { dbField: 'yearOfEstablishment', displayName: 'Year of Estt.' },
                { dbField: 'area', displayName: 'Area (Sq. mt)' },
                { dbField: 'varietyBreed', displayName: 'Variety/Breed' },
                { dbField: 'produce', displayName: 'Produce' },
                { dbField: 'quantity', displayName: 'Qty.' },
                { dbField: 'costOfInputs', displayName: 'Cost of Inputs' },
                { dbField: 'grossIncome', displayName: 'Gross Income' },
                { dbField: 'remarks', displayName: 'Remarks' },
            ],
        },
        {
            id: '10.9',
            title: 'Instructional Farm (crops)',
            description: 'Performance of Instructional Farm (Crops)',
            subsection: true,
            parentSectionId: '10',
            dataSource: 'instructionalFarmCrop',
            format: 'custom',
            customTemplate: 'instructional-farm-crop',
            filters: {
                dateFields: ['createdAt'],
                yearFields: ['reportingYear'],
            },
            fields: [
                { dbField: 'seasonName', displayName: 'Season' },
                { dbField: 'cropName', displayName: 'Name Of the Crop' },
                { dbField: 'area', displayName: 'Area (ha)' },
                { dbField: 'variety', displayName: 'Variety' },
                { dbField: 'typeOfProduce', displayName: 'Type of Produce' },
                { dbField: 'quantity', displayName: 'Qty.' },
                { dbField: 'costOfInputs', displayName: 'Cost of Inputs' },
                { dbField: 'grossIncome', displayName: 'Gross Income' },
                { dbField: 'remarks', displayName: 'Remarks' },
            ],
        },
        {
            id: '10.10',
            title: 'Production Units',
            description: 'Performance of Production Units (Bio-agents/Bio-pesticides/Bio-fertilizers etc.,)',
            subsection: true,
            parentSectionId: '10',
            dataSource: 'productionUnit',
            format: 'custom',
            customTemplate: 'production-unit',
            filters: {
                dateFields: ['createdAt'],
                yearFields: ['reportingYear'],
            },
            fields: [
                { dbField: 'productName', displayName: 'Name of the Product' },
                { dbField: 'quantity', displayName: 'Qty.(Kg)' },
                { dbField: 'costOfInputs', displayName: 'Cost of Inputs' },
                { dbField: 'grossIncome', displayName: 'Gross Income' },
                { dbField: 'remarks', displayName: 'Remarks' },
            ],
        },
        {
            id: '10.11',
            title: 'Instructional Farm (livestock)',
            description: 'Performance of Instructional Farm (livestock and fisheries production)',
            subsection: true,
            parentSectionId: '10',
            dataSource: 'instructionalFarmLivestock',
            format: 'custom',
            customTemplate: 'instructional-farm-livestock',
            filters: {
                dateFields: ['createdAt'],
                yearFields: ['reportingYear'],
            },
            fields: [
                { dbField: 'animalName', displayName: 'Name of the Animal/Bird/Aquatics' },
                { dbField: 'speciesBreed', displayName: 'Species / Breed / Variety' },
                { dbField: 'typeOfProduce', displayName: 'Type of Produce' },
                { dbField: 'quantity', displayName: 'Qty.' },
                { dbField: 'costOfInputs', displayName: 'Cost of Inputs' },
                { dbField: 'grossIncome', displayName: 'Gross Income' },
                { dbField: 'remarks', displayName: 'Remarks' },
            ],
        },
        {
            id: '10.12',
            title: 'Hostel Facilities',
            description: 'Utilization of Hostel Facilities Accommodation Available (No. of Beds)',
            subsection: true,
            parentSectionId: '10',
            dataSource: 'hostelUtilization',
            format: 'custom',
            customTemplate: 'hostel-utilization',
            filters: {
                dateFields: ['createdAt'],
                yearFields: ['reportingYear'],
            },
            fields: [
                { dbField: 'months', displayName: 'Months' },
                { dbField: 'traineesStayed', displayName: 'No. of Trainees Stayed' },
                { dbField: 'traineeDays', displayName: 'Trainee Days (Days Stayed)' },
                { dbField: 'reasonForShortFall', displayName: 'Reason for Short Fall (if any)' },
            ],
        },
        {
            id: '10.13',
            title: 'Staff Quarters',
            description: 'Utilization of Staff Quarters Whether Staff Quarters has been Completed',
            subsection: true,
            parentSectionId: '10',
            dataSource: 'staffQuartersUtilization',
            format: 'custom',
            customTemplate: 'staff-quarters',
            filters: {
                dateFields: ['dateOfCompletion', 'createdAt'],
            },
            fields: [
                { dbField: 'dateOfCompletion', displayName: 'Date of Completion' },
                { dbField: 'numberOfQuarters', displayName: 'No. of Staff Quarters' },
                { dbField: 'occupancyDetails', displayName: 'Occupancy Details' },
                { dbField: 'remark', displayName: 'Remark' },
            ],
        },
        {
            id: '10.14',
            title: 'Rain Water Harvesting',
            description: 'Activities under Rain Water Harvesting structure and micro irrigation system',
            subsection: true,
            parentSectionId: '10',
            dataSource: 'rainwaterHarvesting',
            format: 'custom',
            customTemplate: 'rainwater-harvesting',
            filters: {
                dateFields: ['createdAt'],
                yearFields: ['reportingYear'],
            },
            fields: [
                { dbField: 'trainingProgrammes', displayName: 'No of training programme conducted' },
                { dbField: 'demonstrations', displayName: 'No. of demonstrations' },
                { dbField: 'plantMaterial', displayName: 'No. of plant material produced' },
                { dbField: 'farmerVisits', displayName: 'Visit by the farmers (No.)' },
                { dbField: 'officialVisits', displayName: 'Visit by the officials (No.)' },
            ],
>>>>>>> Stashed changes
        },
    ],
};

/**
 * Get section configuration by ID
 */
function getSectionConfig(sectionId) {
    return reportConfig.sections.find(s => s.id === sectionId);
}

/**
 * Get all sections
 */
function getAllSections() {
    return reportConfig.sections;
}

/**
 * Get sections by data source
 */
function getSectionsByDataSource(dataSource) {
    return reportConfig.sections.filter(s => s.dataSource === dataSource);
}

function getSectionByCustomTemplate(customTemplate) {
    return reportConfig.sections.find(s => s.customTemplate === customTemplate);
}

/**
 * Validate section IDs
 */
function validateSectionIds(sectionIds) {
    const validIds = reportConfig.sections.map(s => s.id);
    const invalidIds = sectionIds.filter(id => !validIds.includes(id));
    if (invalidIds.length > 0) {
        throw new Error(`Invalid section IDs: ${invalidIds.join(', ')}`);
    }
    return true;
}

module.exports = {
    reportConfig,
    getSectionConfig,
    getAllSections,
    getSectionsByDataSource,
    getSectionByCustomTemplate, 
    validateSectionIds,
};
