const express = require('express');
const router = express.Router();

const userRoutes = require('./userRoutes.js');
const authRoutes = require('./authRoutes.js');
const adminRoutes = require('./adminRoutes.js');
const oftFldRoutes = require('./all-masters/oftFldRoutes.js');
const masterDataRoutes = require('./all-masters/masterDataRoutes.js');
const trainingExtensionEventsRoutes = require('./all-masters/trainingExtensionEventsRoutes.js');
const productionProjectsRoutes = require('./all-masters/productionProjectsRoutes.js');
const publicationRoutes = require('./all-masters/publicationRoutes.js');
const otherMastersRoutes = require('./all-masters/otherMastersRoutes.js');
const exportRoutes = require('./exportRoutes.js');
const aboutKvkRoutes = require('./forms/aboutKvkRoutes.js');
const kvkAwardRoutes = require('./forms/kvkAwardRoutes.js');
const scientistAwardRoutes = require('./forms/scientistAwardRoutes.js');
const farmerAwardRoutes = require('./forms/farmerAwardRoutes.js');
const extensionActivityRoutes = require('./forms/extensionActivityRoutes.js');
const otherExtensionActivityRoutes = require('./forms/otherExtensionActivityRoutes.js');
const trainingRoutes = require('./forms/trainingRoutes.js');
const cfldTechnicalParameterRoutes = require('./forms/cfldTechnicalParameterRoutes.js');
const cfldExtensionActivityRoutes = require('./forms/cfldExtensionActivityRoutes.js');
const cfldBudgetUtilizationRoutes = require('./forms/cfldBudgetUtilizationRoutes.js');
const soilWaterRoutes = require('./forms/soilWaterRoutes.js');
const hrdRoutes = require('./forms/hrdRoutes.js');
const techWeekRoutes = require('./forms/techWeekRoutes.js');
const celebrationDayRoutes = require('./forms/celebrationDayRoutes.js');
const productionSupplyRoutes = require('./forms/productionSupplyRoutes.js');
const publicationDetailsRoutes = require('./forms/publicationDetailsRoutes.js');
const fpoManagementRoutes = require('./forms/fpoManagementRoutes.js');
const fpoCbboDetailsRoutes = require('./forms/fpoCbboDetailsRoutes.js');
const seedHubRoutes = require('./forms/seedHubRoutes.js');
const aryaCurrentYearRoutes = require('./forms/aryaCurrentYearRoutes.js');
const aryaPrevYearRoutes = require('./forms/aryaPrevYearRoutes.js');
const oftRoutes = require('./forms/oftRoutes.js');
const fldRoutes = require('./forms/fldRoutes.js');
const csisaRoutes = require('./forms/csisaRoutes.js');
const agriDroneRoutes = require('./forms/agriDroneRoutes.js');
const drmrDetailsRoutes = require('./forms/drmrDetailsRoutes.js');
const nicraRoutes = require('./forms/nicraRoutes.js');
const naturalFarmingRoutes = require('./forms/naturalFarmingRoutes.js');
const kvkOtherProgrammeRoutes = require('./forms/kvkOtherProgrammeRoutes.js');
const craRoutes = require('./forms/craRoutes.js');
const prevalentDiseaseRoutes = require('./forms/prevalentDiseaseRoutes.js');
const nykTrainingRoutes = require('./forms/nykTrainingRoutes.js');
const ppvFraRoutes = require('./forms/ppvFraRoutes.js');
const raweFetRoutes = require('./forms/raweFetRoutes.js');
const vipVisitorsRoutes = require('./forms/vipVisitorsRoutes.js');
const swachhtaBharatRoutes = require('./forms/swachhtaBharatRoutes.js');
const meetingsRoutes = require('./forms/meetingsRoutes.js');
const nariRoutes = require('./forms/nariRoutes.js');
const digitalInformationRoutes = require('./forms/digitalInformationRoutes.js');
const reportRoutes = require('./reports/reportRoutes.js');

// Mount routes
router.use('/auth', authRoutes);
router.use('/admin', adminRoutes);
router.use('/admin', masterDataRoutes);
router.use('/admin/masters', oftFldRoutes);
router.use('/admin/masters', trainingExtensionEventsRoutes);
router.use('/admin/masters', productionProjectsRoutes);
router.use('/admin/masters', publicationRoutes);
router.use('/admin/masters', otherMastersRoutes);
router.use('/admin/masters', exportRoutes);
router.use('/users', userRoutes);
router.use('/forms/about-kvk', aboutKvkRoutes);
router.use('/forms/achievements/kvk-awards', kvkAwardRoutes);
router.use('/forms/achievements/scientist-awards', scientistAwardRoutes);
router.use('/forms/achievements/farmer-awards', farmerAwardRoutes);
router.use('/forms/achievements/extension-activities', extensionActivityRoutes);
router.use('/forms/achievements/other-extension-activities', otherExtensionActivityRoutes);
router.use('/forms/achievements/trainings', trainingRoutes);
router.use('/forms/achievements/cfld-technical-parameters', cfldTechnicalParameterRoutes);
router.use('/forms/achievements/cfld-extension-activities', cfldExtensionActivityRoutes);
router.use('/forms/achievements/cfld-budget-utilizations', cfldBudgetUtilizationRoutes);
router.use('/forms/achievements/soil-water', soilWaterRoutes);
router.use('/forms/achievements/hrd', hrdRoutes);
router.use('/forms/achievements/technology-week', techWeekRoutes);
router.use('/forms/achievements/celebration-days', celebrationDayRoutes);
router.use('/forms/achievements/production-supply', productionSupplyRoutes);
router.use('/forms/achievements/publication-details', publicationDetailsRoutes);
router.use('/forms/achievements/projects/fpo/details', fpoCbboDetailsRoutes);
router.use('/forms/achievements/projects/fpo/management', fpoManagementRoutes);
router.use('/forms/achievements/projects/seed-hub', seedHubRoutes);
router.use('/forms/achievements/projects/arya/current', aryaCurrentYearRoutes);
router.use('/forms/achievements/projects/arya/previous', aryaPrevYearRoutes);
router.use('/forms/achievements/projects/csisa', csisaRoutes);
router.use('/forms/achievements/projects/agri-drone', agriDroneRoutes);
router.use('/forms/achievements/projects/drmr/details', drmrDetailsRoutes);
router.use('/forms/achievements/projects/nicra', nicraRoutes);
router.use('/forms/achievements/projects/cra', craRoutes);
router.use('/forms/achievements/projects/natural-farming', naturalFarmingRoutes);
router.use('/forms/achievements/projects/nari', nariRoutes);
router.use('/forms/achievements/digital-information', digitalInformationRoutes);
router.use('/forms/achievements/other-program', kvkOtherProgrammeRoutes);
router.use('/forms/miscellaneous/prevalent-diseases', prevalentDiseaseRoutes);
router.use('/forms/miscellaneous/nyk-training', nykTrainingRoutes);
router.use('/forms/miscellaneous/ppv-fra', ppvFraRoutes);
router.use('/forms/miscellaneous/rawe-fet', raweFetRoutes);
router.use('/forms/miscellaneous/vip-visitors', vipVisitorsRoutes);
router.use('/forms/miscellaneous/swachhta-bharat', swachhtaBharatRoutes);
router.use('/forms/miscellaneous/meetings', meetingsRoutes);
router.use('/forms/performance/impact', require('./forms/performanceImpactRoutes.js'));
router.use('/forms/performance/infrastructure', require('./forms/performanceInfrastructureRoutes.js'));
router.use('/forms/performance/linkages', require('./forms/performanceLinkageRoutes.js'));
router.use('/forms/performance/district-village', require('./forms/performanceDistrictVillageRoutes.js'));
router.use('/forms/performance/financial', require('./forms/performanceFinancialRoutes.js'));
router.use('/forms/achievements/oft', oftRoutes);
router.use('/forms/achievements/fld/extension-training', require('./forms/fldExtensionRoutes.js'));
router.use('/forms/achievements/fld/technical-feedback', require('./forms/fldTechnicalFeedbackRoutes.js'));
router.use('/forms/achievements/fld', fldRoutes);
router.use('/reports', reportRoutes);





module.exports = router;
