import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { ENTITY_TYPES } from '../constants/entityConstants'
import { apiClient } from '../services/api'
import { ROUTE_PATHS } from '../constants/routePaths'

const EMPTY_ARRAY: any[] = []

/**
 * Generic hook for project data when specific hooks are not yet implemented.
 * This allows the DataManagementView to render even if data is empty.
 */
export function useProjectData(entityType: string) {
    const queryClient = useQueryClient()
    const P = ROUTE_PATHS.PROJECT_DATA_API
    const NARI_FORM = ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NARI.FORM_API
    const A = ROUTE_PATHS.ACHIEVEMENTS

    // Map entity types to their specific backend endpoints
    const endpointMap: Record<string, string> = {
        [ENTITY_TYPES.ACHIEVEMENT_AWARD_KVK]: P.ACHIEVEMENTS.AWARD_KVK,
        [ENTITY_TYPES.ACHIEVEMENT_AWARD_SCIENTIST]:
            P.ACHIEVEMENTS.AWARD_SCIENTIST,
        [ENTITY_TYPES.ACHIEVEMENT_AWARD_FARMER]: P.ACHIEVEMENTS.AWARD_FARMER,
        [ENTITY_TYPES.ACHIEVEMENT_EXTENSION]:
            P.ACHIEVEMENTS.EXTENSION_ACTIVITIES,
        [ENTITY_TYPES.ACHIEVEMENT_OTHER_EXTENSION]:
            P.ACHIEVEMENTS.OTHER_EXTENSION_ACTIVITIES,
        [ENTITY_TYPES.ACHIEVEMENT_TECHNOLOGY_WEEK]:
            P.ACHIEVEMENTS.TECHNOLOGY_WEEK,
        [ENTITY_TYPES.ACHIEVEMENT_CELEBRATION_DAYS]:
            P.ACHIEVEMENTS.CELEBRATION_DAYS,
        [ENTITY_TYPES.ACHIEVEMENT_PRODUCTION_SUPPLY]:
            P.ACHIEVEMENTS.PRODUCTION_SUPPLY,
        [ENTITY_TYPES.ACHIEVEMENT_PUBLICATION_DETAILS]:
            P.ACHIEVEMENTS.PUBLICATION_DETAILS,
        [ENTITY_TYPES.PROJECT_CFLD_TECHNICAL_PARAM]:
            P.ACHIEVEMENTS.CFLD.TECHNICAL_PARAMETERS,
        [ENTITY_TYPES.PROJECT_CFLD_EXTENSION_ACTIVITY]:
            P.ACHIEVEMENTS.CFLD.EXTENSION_ACTIVITIES,
        [ENTITY_TYPES.PROJECT_CFLD_BUDGET]:
            P.ACHIEVEMENTS.CFLD.BUDGET_UTILIZATIONS,
        [ENTITY_TYPES.ACHIEVEMENT_SOIL_EQUIPMENT]:
            P.ACHIEVEMENTS.SOIL_WATER.EQUIPMENTS,
        [ENTITY_TYPES.ACHIEVEMENT_SOIL_ANALYSIS]:
            P.ACHIEVEMENTS.SOIL_WATER.ANALYSIS,
        [ENTITY_TYPES.ACHIEVEMENT_WORLD_SOIL_DAY]:
            P.ACHIEVEMENTS.SOIL_WATER.WORLD_SOIL_DAY,
        [ENTITY_TYPES.ACHIEVEMENT_HRD]: P.ACHIEVEMENTS.HRD,
        [ENTITY_TYPES.PROJECT_FPO_DETAILS]: P.PROJECTS.FPO_DETAILS,
        [ENTITY_TYPES.PROJECT_FPO_MANAGEMENT]: P.PROJECTS.FPO_MANAGEMENT,
        [ENTITY_TYPES.PROJECT_SEED_HUB]: P.PROJECTS.SEED_HUB,
        [ENTITY_TYPES.PROJECT_ARYA_CURRENT]: P.PROJECTS.ARYA_CURRENT,
        [ENTITY_TYPES.PROJECT_ARYA_EVALUATION]: P.PROJECTS.ARYA_EVALUATION,
        [ENTITY_TYPES.PROJECT_CSISA]: P.PROJECTS.CSISA,
        [ENTITY_TYPES.PROJECT_TSP_SCSP]: P.PROJECTS.TSP_SCSP,
        [ENTITY_TYPES.PROJECT_AGRI_DRONE]: P.PROJECTS.AGRI_DRONE,
        [ENTITY_TYPES.PROJECT_AGRI_DRONE_DEMO]: P.PROJECTS.AGRI_DRONE_DEMO,
        [ENTITY_TYPES.PROJECT_DRMR_DETAILS]: P.PROJECTS.DRMR_DETAILS,
        [ENTITY_TYPES.PROJECT_DRMR_ACTIVITY]: P.PROJECTS.DRMR_ACTIVITY,
        [ENTITY_TYPES.PROJECT_NICRA_BASIC]: P.PROJECTS.NICRA.BASIC,
        [ENTITY_TYPES.PROJECT_NICRA_DETAILS]: P.PROJECTS.NICRA.DETAILS,
        [ENTITY_TYPES.PROJECT_NICRA_TRAINING]: P.PROJECTS.NICRA.TRAINING,
        [ENTITY_TYPES.PROJECT_NICRA_EXTENSION]: P.PROJECTS.NICRA.EXTENSION,
        [ENTITY_TYPES.PROJECT_NICRA_INTERVENTION]:
            P.PROJECTS.NICRA.INTERVENTION,
        [ENTITY_TYPES.PROJECT_NICRA_REVENUE]: P.PROJECTS.NICRA.REVENUE,
        [ENTITY_TYPES.PROJECT_NICRA_CUSTOM_HIRING]:
            P.PROJECTS.NICRA.CUSTOM_HIRING,
        [ENTITY_TYPES.PROJECT_NICRA_VCRMC]: P.PROJECTS.NICRA.VCRMC,
        [ENTITY_TYPES.PROJECT_NICRA_SOIL_HEALTH]: P.PROJECTS.NICRA.SOIL_HEALTH,
        [ENTITY_TYPES.PROJECT_NICRA_CONVERGENCE]: P.PROJECTS.NICRA.CONVERGENCE,
        [ENTITY_TYPES.PROJECT_NICRA_DIGNITARIES]: P.PROJECTS.NICRA.DIGNITARIES,
        [ENTITY_TYPES.PROJECT_NICRA_PI_COPI]: P.PROJECTS.NICRA.PI_COPI,
        [ENTITY_TYPES.PROJECT_CRA_DETAILS]: P.PROJECTS.CRA_DETAILS,
        [ENTITY_TYPES.PROJECT_CRA_EXTENSION_ACTIVITY]:
            P.PROJECTS.CRA_EXTENSION_ACTIVITY,
        [ENTITY_TYPES.PROJECT_NARI_NUTRI_GARDEN]: NARI_FORM.NUTRITIONAL_GARDEN,
        [ENTITY_TYPES.PROJECT_NARI_BIO_FORTIFIED]: NARI_FORM.BIO_FORTIFIED_CROP,
        [ENTITY_TYPES.PROJECT_NARI_VALUE_ADDITION]: NARI_FORM.VALUE_ADDITION,
        [ENTITY_TYPES.PROJECT_NARI_TRAINING]: P.PROJECTS.NARI_TRAINING,
        [ENTITY_TYPES.PROJECT_NARI_EXTENSION]: P.PROJECTS.NARI_EXTENSION,
        [ENTITY_TYPES.PROJECT_NATURAL_FARMING_GEO]: P.NATURAL_FARMING.GEO,
        [ENTITY_TYPES.PROJECT_NATURAL_FARMING_PHYSICAL]:
            P.NATURAL_FARMING.PHYSICAL,
        [ENTITY_TYPES.PROJECT_NATURAL_FARMING_DEMO]: P.NATURAL_FARMING.DEMO,
        [ENTITY_TYPES.PROJECT_NATURAL_FARMING_FARMERS]:
            P.NATURAL_FARMING.FARMERS,
        [ENTITY_TYPES.PROJECT_NATURAL_FARMING_BENEFICIARIES]:
            P.NATURAL_FARMING.BENEFICIARIES,
        [ENTITY_TYPES.PROJECT_NATURAL_FARMING_SOIL]: P.NATURAL_FARMING.SOIL,
        [ENTITY_TYPES.PROJECT_NATURAL_FARMING_BUDGET]: P.NATURAL_FARMING.BUDGET,
        [ENTITY_TYPES.PROJECT_OTHER]: P.OTHER_PROGRAM,
        [ENTITY_TYPES.ACHIEVEMENT_OFT]: A.OFT,
        [ENTITY_TYPES.ACHIEVEMENT_FLD]: A.FLD.BASE,
        [ENTITY_TYPES.ACHIEVEMENT_FLD_EXTENSION_TRAINING]:
            A.FLD.EXTENSION_TRAINING,
        [ENTITY_TYPES.ACHIEVEMENT_FLD_TECHNICAL_FEEDBACK]:
            A.FLD.TECHNICAL_FEEDBACK,
        [ENTITY_TYPES.ACHIEVEMENT_TRAINING]: A.TRAININGS,
        [ENTITY_TYPES.MISC_PREVALENT_DISEASES_CROPS]:
            P.MISCELLANEOUS.PREVALENT_DISEASES_CROPS,
        [ENTITY_TYPES.MISC_PREVALENT_DISEASES_LIVESTOCK]:
            P.MISCELLANEOUS.PREVALENT_DISEASES_LIVESTOCK,
        [ENTITY_TYPES.MISC_NYK_TRAINING]: P.MISCELLANEOUS.NYK_TRAINING,
        [ENTITY_TYPES.MISC_PPV_FRA_TRAINING]: P.MISCELLANEOUS.PPV_FRA_TRAINING,
        [ENTITY_TYPES.MISC_PPV_FRA_PLANT_VARIETIES]:
            P.MISCELLANEOUS.PPV_FRA_PLANT_VARIETIES,
        [ENTITY_TYPES.MISC_RAWE_FET]: P.MISCELLANEOUS.RAWE_FET,
        [ENTITY_TYPES.MISC_VIP_VISITORS]: P.MISCELLANEOUS.VIP_VISITORS,
        [ENTITY_TYPES.MISC_SWACHHTA_SEWA]: P.MISCELLANEOUS.SWACHHTA_SEWA,
        [ENTITY_TYPES.MISC_SWACHHTA_PAKHWADA]:
            P.MISCELLANEOUS.SWACHHTA_PAKHWADA,
        [ENTITY_TYPES.MISC_SWACHHTA_BUDGET]: P.MISCELLANEOUS.SWACHHTA_BUDGET,
        [ENTITY_TYPES.MISC_MEETINGS_SAC]: P.MISCELLANEOUS.MEETINGS_SAC,
        [ENTITY_TYPES.MISC_MEETINGS_OTHER]: P.MISCELLANEOUS.MEETINGS_OTHER,
        [ENTITY_TYPES.PERFORMANCE_IMPACT_KVK_ACTIVITIES]:
            P.PERFORMANCE.IMPACT_KVK_ACTIVITIES,
        [ENTITY_TYPES.PERFORMANCE_IMPACT_ENTREPRENEURSHIP]:
            P.PERFORMANCE.IMPACT_ENTREPRENEURSHIP,
        [ENTITY_TYPES.PERFORMANCE_IMPACT_SUCCESS_STORIES]:
            P.PERFORMANCE.IMPACT_SUCCESS_STORIES,
        [ENTITY_TYPES.PERFORMANCE_DEMONSTRATION_UNITS]:
            P.PERFORMANCE.DEMONSTRATION_UNITS,
        [ENTITY_TYPES.PERFORMANCE_INSTRUCTIONAL_FARM_CROPS]:
            P.PERFORMANCE.INSTRUCTIONAL_FARM_CROPS,
        [ENTITY_TYPES.PERFORMANCE_PRODUCTION_UNITS]:
            P.PERFORMANCE.PRODUCTION_UNITS,
        [ENTITY_TYPES.PERFORMANCE_INSTRUCTIONAL_FARM_LIVESTOCK]:
            P.PERFORMANCE.INSTRUCTIONAL_FARM_LIVESTOCK,
        [ENTITY_TYPES.PERFORMANCE_HOSTEL]: P.PERFORMANCE.HOSTEL,
        [ENTITY_TYPES.PERFORMANCE_STAFF_QUARTERS]: P.PERFORMANCE.STAFF_QUARTERS,
        [ENTITY_TYPES.PERFORMANCE_RAINWATER_HARVESTING]:
            P.PERFORMANCE.RAINWATER_HARVESTING,
        [ENTITY_TYPES.PERFORMANCE_FUNCTIONAL_LINKAGE]:
            P.PERFORMANCE.FUNCTIONAL_LINKAGE,
        [ENTITY_TYPES.PERFORMANCE_SPECIAL_PROGRAMMES]:
            P.PERFORMANCE.SPECIAL_PROGRAMMES,
        [ENTITY_TYPES.PERFORMANCE_OPERATIONAL_AREA]:
            P.PERFORMANCE.OPERATIONAL_AREA,
        [ENTITY_TYPES.PERFORMANCE_VILLAGE_ADOPTION]:
            P.PERFORMANCE.VILLAGE_ADOPTION,
        [ENTITY_TYPES.PERFORMANCE_PRIORITY_THRUST]:
            P.PERFORMANCE.PRIORITY_THRUST,
        [ENTITY_TYPES.PERFORMANCE_DISTRICT_LEVEL]: P.PERFORMANCE.DISTRICT_LEVEL,
        [ENTITY_TYPES.PERFORMANCE_BUDGET_DETAILS]: P.PERFORMANCE.BUDGET_DETAILS,
        [ENTITY_TYPES.PERFORMANCE_REVOLVING_FUND]: P.PERFORMANCE.REVOLVING_FUND,
        [ENTITY_TYPES.PERFORMANCE_REVENUE_GENERATION]:
            P.PERFORMANCE.REVENUE_GENERATION,
        [ENTITY_TYPES.PERFORMANCE_RESOURCE_GENERATION]:
            P.PERFORMANCE.RESOURCE_GENERATION,
        [ENTITY_TYPES.PERFORMANCE_PROJECT_BUDGET]: P.PERFORMANCE.PROJECT_BUDGET,
        [ENTITY_TYPES.MISC_DIGITAL_MOBILE_APP]:
            P.DIGITAL_INFORMATION.MOBILE_APP,
        [ENTITY_TYPES.MISC_DIGITAL_WEB_PORTAL]:
            P.DIGITAL_INFORMATION.WEB_PORTAL,
        [ENTITY_TYPES.MISC_DIGITAL_KISAN_SARATHI]:
            P.DIGITAL_INFORMATION.KISAN_SARATHI,
        [ENTITY_TYPES.MISC_DIGITAL_KISAN_MOBILE_ADVISORY]:
            P.DIGITAL_INFORMATION.KMAS,
        [ENTITY_TYPES.MISC_DIGITAL_OTHER_CHANNELS]:
            P.DIGITAL_INFORMATION.MSG_DETAILS,
    }

    const endpoint =
        endpointMap[entityType] || `/forms/achievements/${entityType}s`

    const query = useQuery({
        queryKey: ['project-data', entityType],
        queryFn: async () => {
            try {
                const res = await apiClient.get<any>(endpoint)
                // Handle both { success: true, data: [...] } and direct array responses
                const data = res?.data || (Array.isArray(res) ? res : null)
                return data || EMPTY_ARRAY
            } catch (err) {
                console.warn(
                    `No API or error for ${entityType}, returning empty array:`,
                    err
                )
                return EMPTY_ARRAY
            }
        },
        retry: false,
    })

    const createMutation = useMutation({
        mutationFn: (data: any) => apiClient.post(endpoint, data),
        onSuccess: async () => {
            await queryClient.invalidateQueries({
                queryKey: ['project-data', entityType],
                exact: true,
                refetchType: 'active',
            })
        },
    })

    const updateMutation = useMutation({
        mutationFn: ({ id, data }: { id: number | string; data: any }) =>
            apiClient.put(`${endpoint}/${id}`, data),
        onSuccess: async () => {
            await queryClient.invalidateQueries({
                queryKey: ['project-data', entityType],
                exact: true,
                refetchType: 'active',
            })
        },
    })

    const deleteMutation = useMutation({
        mutationFn: (id: number | string) =>
            apiClient.delete(`${endpoint}/${id}`),
        onSuccess: async () => {
            await queryClient.invalidateQueries({
                queryKey: ['project-data', entityType],
                exact: true,
                refetchType: 'active',
            })
        },
    })

    return {
        data: query.data || EMPTY_ARRAY,
        isLoading: query.isLoading,
        error: query.error,
        create: createMutation.mutateAsync,
        update: updateMutation.mutateAsync,
        remove: deleteMutation.mutateAsync,
        isCreating: createMutation.isPending,
        isUpdating: updateMutation.isPending,
        isDeleting: deleteMutation.isPending,
    }
}
