const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

process.env.DATABASE_URL ||= 'postgresql://test:test@localhost:5432/test';

const { validateFormRobustness } = require('../middleware/validateFormRobustness.js');
const prisma = require('../config/prisma.js');
const nicraRevenueRepository = require('../repositories/forms/nicraRevenueRepository.js');
const nicraFarmImplementRepository = require('../repositories/forms/nicraFarmImplementRepository.js');
const nicraReportRepository = require('../repositories/reports/nicraReport/nicraReportRepository.js');
const {
    buildOperationalAreaDetailsTabularData,
} = require('../services/reports/formsTemplate/districtVillageTemplates/operationalAreaDetailsTemplate.js');
const {
    renderPrevalentDiseasesLivestockSection,
} = require('../services/reports/formsTemplate/miscTemplates/prevalentDiseasesTemplate.js');
const {
    renderCsisaSection,
} = require('../services/reports/formsTemplate/projectTemplates/csisaTemplate.js');
const {
    buildNicraFarmImplementGroups,
} = require('../services/reports/formsTemplate/projectTemplates/nicraFarmImplementTemplate.js');

const ROOT = path.resolve(__dirname, '..');

function read(relativePath) {
    return fs.readFileSync(path.join(ROOT, relativePath), 'utf8');
}

function validate(body) {
    let forwarded;
    validateFormRobustness({ body }, {}, (error) => {
        forwarded = error;
    });
    if (forwarded) throw forwarded;
}

const reportContext = {
    _escapeHtml: (value) => String(value ?? ''),
    _generateEmptySection: () => '',
};

function farmImplementRecord(overrides = {}) {
    return {
        nicraFarmImplementId: 1,
        kvkId: 1,
        reportingYear: new Date('2026-01-01T00:00:00.000Z'),
        startDate: new Date('2026-01-01T00:00:00.000Z'),
        endDate: new Date('2026-01-02T00:00:00.000Z'),
        nameOfFarmImplement: 'Seed drill',
        areaCovered: 10.25,
        farmImplementUsedHours: 40.5,
        revenueGeneratedRs: 2050.25,
        expenditureIncurredRepairingRs: 100.5,
        generalM: 1,
        generalF: 1,
        obcM: 0,
        obcF: 0,
        scM: 0,
        scF: 0,
        stM: 0,
        stF: 0,
        photographs: '',
        kvk: {
            kvkName: 'Test KVK',
            state: { stateName: 'Bihar' },
        },
        ...overrides,
    };
}

test('BLA-57 requested numeric fields accept decimals while animal counts remain whole numbers', () => {
    assert.doesNotThrow(() => validate({
        mortalityCount: '12.5',
        revenue: '305218.90',
        farmImplementUsedHours: '40.5',
        farmImplementUsedInHours: '5.5',
        revenueGeneratedRs: '2050.25',
        revenueGeneratedByFarmImplement: '50.50',
    }));

    assert.throws(
        () => validate({ animalsTreated: '12.5' }),
        /Field "animalsTreated" must be a whole number/,
    );
});

test('BLA-57 web forms and table/export labels use the requested terminology', () => {
    const districtForm = read('../frontend/src/pages/dashboard/shared/forms/performance-indicators/DistrictAndVillageForms.tsx');
    const diseaseForm = read('../frontend/src/pages/dashboard/shared/forms/miscellaneous/PrevalentDiseasesForms.tsx');
    const csisaForm = read('../frontend/src/pages/dashboard/shared/forms/projects/CsisaForms.tsx');
    const nicraForm = read('../frontend/src/pages/dashboard/shared/forms/projects/NicraForms.tsx');
    const exportUtils = read('../frontend/src/utils/exportUtils.ts');

    assert.match(districtForm, /label="Taluka"/);
    assert.match(diseaseForm, /label="Mortality \(%\)"/);
    assert.match(diseaseForm, /label="No\. of Animals Treated"/);
    assert.match(csisaForm, /label="Trial Name"/);
    assert.doesNotMatch(csisaForm, /Trall Name|Trail Name/);

    assert.match(nicraForm, /label="Revenue"[\s\S]*?type="number"[\s\S]*?step="0\.01"/);
    assert.match(nicraForm, /label="Farm Implement used \(In Hours\)"[\s\S]*?type="number"[\s\S]*?step="0\.01"/);
    assert.match(nicraForm, /label="Revenue generated by Farm Implement \(Rs\.\)"[\s\S]*?type="number"[\s\S]*?step="0\.01"/);

    assert.match(exportUtils, /'taluk': 'Taluka'/);
    assert.match(exportUtils, /'mortalityCount': 'Mortality \(%\)'/);
    assert.match(exportUtils, /'animalsTreated': 'No\. of Animals Treated'/);
    assert.match(exportUtils, /'trialName': 'Trial Name'/);
});

test('BLA-57 Soil & Water and DRMR labels use consistent spelling without changing data keys', () => {
    const soilWaterForm = read('../frontend/src/pages/dashboard/shared/forms/SoilWaterTestingForms.tsx');
    const drmrForm = read('../frontend/src/pages/dashboard/shared/forms/projects/DrmrForms.tsx');
    const exportUtils = read('../frontend/src/utils/exportUtils.ts');
    const stateReport = read('services/reports/formsTemplate/achievementTemplates/soilWaterAnalysisDetailStateReportTemplate.js');
    const samplesReport = read('services/reports/formsTemplate/achievementTemplates/soilWaterSamplesBPageReportTemplate.js');

    assert.match(soilWaterForm, /label="Samples Analysed Through"/);
    assert.match(soilWaterForm, /label="Please specify how samples were analysed"/);
    assert.match(soilWaterForm, /label="No\. of Samples Analysed"/);
    assert.doesNotMatch(soilWaterForm, /analyzed/i);
    assert.match(exportUtils, /'noOfSamplesAnalyzed': 'No\. of Samples Analysed'/);
    assert.doesNotMatch(stateReport, /analyzed/i);
    assert.doesNotMatch(samplesReport, /analyzed/i);

    assert.match(drmrForm, /label="Varieties used in Farmer Practice"/);
    assert.match(drmrForm, /label="Yield Farmer Practice\(Kg\/ha\)"/);
    assert.doesNotMatch(drmrForm, /label="[^"]*Practise/);
    assert.match(drmrForm, /formData\.varietiesFarmerPractise/);
    assert.match(drmrForm, /formData\.yieldFarmerPractise/);
});

test('BLA-57 report and export headings use Taluka, mortality, treated-animal, and Trial terminology', () => {
    const operational = buildOperationalAreaDetailsTabularData([{ taluk: 'Patna Sadar' }]);
    assert.equal(operational.headers[2], 'Name of Taluka');

    const livestockHtml = renderPrevalentDiseasesLivestockSection.call(
        reportContext,
        { id: '5.2', title: 'Prevalent Diseases in Livestock' },
        [{
            diseaseName: 'Disease',
            livestockType: 'Cattle',
            mortalityCount: 12.5,
            animalsTreated: 20,
            preventiveMeasures: 'Vaccination',
        }],
        'livestock-diseases',
        true,
    );
    assert.match(livestockHtml, /<th>Mortality \(%\)<\/th>/);
    assert.match(livestockHtml, /<th>No\. of Animals Treated<\/th>/);

    const csisaHtml = renderCsisaSection.call(
        reportContext,
        { id: '2.32', title: 'CSISA' },
        [{ trialName: 'Decimal trial' }],
        'csisa',
        true,
    );
    assert.match(csisaHtml, /<th class="wide">Trial Name<\/th>/);
    assert.doesNotMatch(csisaHtml, /Trail Name|Trall Name/);

    const reportConfig = read('config/reportConfig.js');
    assert.match(reportConfig, /dbField: 'taluk', displayName: 'Name of Taluka'/);
});

test('BLA-57 NICRA Revenue Generated supports decimal create, edit, and view', async () => {
    const originalCreate = prisma.nicraRevenueGenerated.create;
    const originalFindFirst = prisma.nicraRevenueGenerated.findFirst;
    const originalUpdate = prisma.nicraRevenueGenerated.update;
    let stored = {
        nicraRevenueGeneratedId: 1,
        kvkId: 1,
        reportingYear: new Date('2026-01-01T00:00:00.000Z'),
        revenue: 305218.9,
    };

    prisma.nicraRevenueGenerated.create = async ({ data }) => {
        stored = { ...stored, ...data };
        return stored;
    };
    prisma.nicraRevenueGenerated.findFirst = async () => stored;
    prisma.nicraRevenueGenerated.update = async ({ data }) => {
        stored = { ...stored, ...data };
        return stored;
    };

    try {
        const created = await nicraRevenueRepository.create({
            kvkId: 1,
            reportingYear: '2026-01-01',
            revenue: '305218.90',
        });
        const updated = await nicraRevenueRepository.update(1, { revenue: '12500.75' });
        const viewed = await nicraRevenueRepository.findById(1);

        assert.equal(created.revenue, 305218.9);
        assert.equal(updated.revenue, 12500.75);
        assert.equal(viewed.revenue, 12500.75);
    } finally {
        prisma.nicraRevenueGenerated.create = originalCreate;
        prisma.nicraRevenueGenerated.findFirst = originalFindFirst;
        prisma.nicraRevenueGenerated.update = originalUpdate;
    }
});

test('BLA-57 NICRA Custom Hiring supports decimal create, edit, and view', async () => {
    const originalCreate = prisma.nicraFarmImplement.create;
    const originalFindFirst = prisma.nicraFarmImplement.findFirst;
    const originalUpdate = prisma.nicraFarmImplement.update;
    let stored = farmImplementRecord();

    prisma.nicraFarmImplement.create = async ({ data }) => {
        stored = farmImplementRecord(data);
        return stored;
    };
    prisma.nicraFarmImplement.findFirst = async () => stored;
    prisma.nicraFarmImplement.update = async ({ data }) => {
        stored = { ...stored, ...data };
        return stored;
    };

    try {
        const created = await nicraFarmImplementRepository.create({
            kvkId: 1,
            reportingYear: '2026-01-01',
            startDate: '2026-01-01',
            endDate: '2026-01-02',
            nameOfFarmImplement: 'Seed drill',
            farmImplementUsedHours: '40.5',
            revenueGeneratedRs: '2050.25',
        });
        const updated = await nicraFarmImplementRepository.update(1, {
            farmImplementUsedHours: '5.5',
            revenueGeneratedRs: '50.50',
        });
        const viewed = await nicraFarmImplementRepository.findById(1);

        assert.equal(created.farmImplementUsedHours, 40.5);
        assert.equal(created.revenueGeneratedRs, 2050.25);
        assert.equal(updated.farmImplementUsedHours, 5.5);
        assert.equal(updated.revenueGeneratedRs, 50.5);
        assert.equal(viewed.farmImplementUsedInHours, 5.5);
        assert.equal(viewed.revenueGeneratedByFarmImplement, 50.5);
    } finally {
        prisma.nicraFarmImplement.create = originalCreate;
        prisma.nicraFarmImplement.findFirst = originalFindFirst;
        prisma.nicraFarmImplement.update = originalUpdate;
    }
});

test('BLA-57 NICRA report data and Custom Hiring report preserve decimals', async () => {
    const originalRevenueFindMany = prisma.nicraRevenueGenerated.findMany;
    const originalFarmFindMany = prisma.nicraFarmImplement.findMany;

    prisma.nicraRevenueGenerated.findMany = async () => [{
        nicraRevenueGeneratedId: 1,
        kvkId: 1,
        revenue: 12500.75,
        kvk: { kvkName: 'Test KVK', state: { stateName: 'Bihar' } },
    }];
    prisma.nicraFarmImplement.findMany = async () => [farmImplementRecord({
        farmImplementUsedHours: 5.5,
        revenueGeneratedRs: 2050.25,
    })];

    try {
        const revenueRows = await nicraReportRepository.getNicraRevenueGeneratedData(1);
        const farmRows = await nicraReportRepository.getNicraFarmImplementData(1);
        const groups = buildNicraFarmImplementGroups(farmRows);

        assert.equal(revenueRows[0].revenueGeneratedRs, 12500.75);
        assert.equal(groups.groups[0].rows[0].farmImplementUsedHours, 5.5);
        assert.equal(groups.groups[0].rows[0].revenueGeneratedRs, 2050.25);
    } finally {
        prisma.nicraRevenueGenerated.findMany = originalRevenueFindMany;
        prisma.nicraFarmImplement.findMany = originalFarmFindMany;
    }
});
