/**
 * Achievements Routes Configuration
 *
 * Contains all route configurations for the "Achievements" section.
 * Includes routes for OFT, FLD, Trainings, Extension Activities, Production & Supply,
 * Publications, Soil & Water Testing, Awards, and HRD.
 */

import { ROUTE_PATHS } from '../../constants/routePaths'
import { FIELD_GROUPS } from '../../constants/fieldNames'
import { ROUTE_SIBLING_GROUPS } from '../routeSiblingGroups'
import { RouteConfig } from './types'

export const achievementsRoutes: RouteConfig[] = [
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.OFT,
        title: 'On Farm Trials (OFT)',
        category: 'Form Management',
        subcategory: 'Achievements',
        parent: ROUTE_PATHS.ACHIEVEMENTS.BASE,
        moduleCode: 'achievements_oft',
        fields: FIELD_GROUPS.OFT,
        siblings: ROUTE_SIBLING_GROUPS.OFT,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.FLD.BASE,
        title: 'Front Line Demonstrations (FLD)',
        category: 'Form Management',
        subcategory: 'Achievements',
        parent: ROUTE_PATHS.ACHIEVEMENTS.BASE,
        moduleCode: 'achievements_fld',
        fields: FIELD_GROUPS.FLD_BASE,
        siblings: ROUTE_SIBLING_GROUPS.FLD,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.FLD.EXTENSION_TRAINING,
        title: 'Extension & Training activities under FLD',
        category: 'Form Management',
        subcategory: 'Achievements',
        parent: ROUTE_PATHS.ACHIEVEMENTS.BASE,
        moduleCode: 'achievements_fld_extension_training',
        fields: FIELD_GROUPS.FLD_EXTENSION_TRAINING,
        siblings: ROUTE_SIBLING_GROUPS.FLD,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.FLD.TECHNICAL_FEEDBACK,
        title: 'Technical Feedback on FLD',
        category: 'Form Management',
        subcategory: 'Achievements',
        parent: ROUTE_PATHS.ACHIEVEMENTS.BASE,
        moduleCode: 'achievements_fld_technical_feedback',
        fields: FIELD_GROUPS.FLD_TECHNICAL_FEEDBACK,
        siblings: ROUTE_SIBLING_GROUPS.FLD,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.TRAININGS,
        title: 'Trainings',
        category: 'Form Management',
        subcategory: 'Achievements',
        parent: ROUTE_PATHS.ACHIEVEMENTS.BASE,
        moduleCode: 'achievements_trainings',
        fields: FIELD_GROUPS.TRAININGS,
        siblings: ROUTE_SIBLING_GROUPS.TRAINING,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.EXTENSION_ACTIVITIES,
        title: 'Extension Activities',
        category: 'Form Management',
        subcategory: 'Achievements',
        parent: ROUTE_PATHS.ACHIEVEMENTS.BASE,
        moduleCode: 'achievements_extension_activities',
        fields: FIELD_GROUPS.EXTENSION_ACTIVITIES,
        siblings: ROUTE_SIBLING_GROUPS.EXTENSION,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.OTHER_EXTENSION,
        title: 'Other Extension Activities',
        category: 'Form Management',
        subcategory: 'Achievements',
        parent: ROUTE_PATHS.ACHIEVEMENTS.BASE,
        moduleCode: 'achievements_other_extension_activities',
        fields: FIELD_GROUPS.OTHER_EXTENSION,
        siblings: ROUTE_SIBLING_GROUPS.EXTENSION,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.TECHNOLOGY_WEEK,
        title: 'Technology Week Celebration',
        category: 'Form Management',
        subcategory: 'Achievements',
        parent: ROUTE_PATHS.ACHIEVEMENTS.BASE,
        moduleCode: 'achievements_technology_week_celebration',
        fields: FIELD_GROUPS.TECHNOLOGY_WEEK,
        siblings: ROUTE_SIBLING_GROUPS.SPECIAL_DAYS,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.CELEBRATION_DAYS,
        title: 'Celebration Days',
        category: 'Form Management',
        subcategory: 'Achievements',
        parent: ROUTE_PATHS.ACHIEVEMENTS.BASE,
        moduleCode: 'achievements_celebration_days',
        fields: FIELD_GROUPS.CELEBRATION_DAYS,
        siblings: ROUTE_SIBLING_GROUPS.SPECIAL_DAYS,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.POSHAN_MAHA,
        title: 'Poshan Maha',
        category: 'Form Management',
        subcategory: 'Achievements',
        parent: ROUTE_PATHS.ACHIEVEMENTS.BASE,
        moduleCode: 'achievements_celebration_days',
        fields: FIELD_GROUPS.POSHAN_MAHA,
        siblings: ROUTE_SIBLING_GROUPS.SPECIAL_DAYS,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PRODUCTION_SUPPLY,
        title: 'Production and supply of Technological products',
        category: 'Form Management',
        subcategory: 'Achievements',
        parent: ROUTE_PATHS.ACHIEVEMENTS.BASE,
        moduleCode: 'achievements_production_supply_tech_products',
        fields: FIELD_GROUPS.PRODUCTION_SUPPLY,
        siblings: [ROUTE_PATHS.ACHIEVEMENTS.PRODUCTION_SUPPLY],
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PUBLICATIONS,
        title: 'KVKs Publication Details',
        category: 'Form Management',
        subcategory: 'Achievements',
        parent: ROUTE_PATHS.ACHIEVEMENTS.BASE,
        moduleCode: 'achievements_publications',
        fields: FIELD_GROUPS.PUBLICATIONS,
        siblings: [ROUTE_PATHS.ACHIEVEMENTS.PUBLICATIONS],
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.SOIL_ANALYSIS,
        title: 'Soil, Water and Plant analysis',
        category: 'Form Management',
        subcategory: 'Achievements',
        parent: ROUTE_PATHS.ACHIEVEMENTS.BASE,
        moduleCode: 'achievements_soil_water_testing',
        fields: FIELD_GROUPS.SOIL_ANALYSIS,
        siblings: ROUTE_SIBLING_GROUPS.SOIL_WATER_TESTING,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.WORLD_SOIL_DAY,
        title: 'World Soil Day',
        category: 'Form Management',
        subcategory: 'Achievements',
        parent: ROUTE_PATHS.ACHIEVEMENTS.BASE,
        moduleCode: 'achievements_soil_water_testing',
        fields: FIELD_GROUPS.WORLD_SOIL_DAY,
        siblings: ROUTE_SIBLING_GROUPS.SPECIAL_DAYS,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.AWARDS.KVK,
        title: 'Awards (KVK)',
        category: 'Form Management',
        subcategory: 'Achievements',
        parent: ROUTE_PATHS.ACHIEVEMENTS.BASE,
        moduleCode: 'achievements_award_recognition',
        fields: FIELD_GROUPS.AWARDS_KVK,
        siblings: ROUTE_SIBLING_GROUPS.AWARDS,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.AWARDS.SCIENTIST,
        title: 'Scientist',
        category: 'Form Management',
        subcategory: 'Achievements',
        parent: ROUTE_PATHS.ACHIEVEMENTS.BASE,
        moduleCode: 'achievements_award_recognition',
        fields: FIELD_GROUPS.AWARDS_SCIENTIST,
        siblings: ROUTE_SIBLING_GROUPS.AWARDS,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.AWARDS.FARMER,
        title: 'Farmer',
        category: 'Form Management',
        subcategory: 'Achievements',
        parent: ROUTE_PATHS.ACHIEVEMENTS.BASE,
        moduleCode: 'achievements_award_recognition',
        fields: FIELD_GROUPS.AWARDS_FARMER,
        siblings: ROUTE_SIBLING_GROUPS.AWARDS,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.HRD,
        title: 'Human-Resource Development',
        category: 'Form Management',
        subcategory: 'Achievements',
        parent: ROUTE_PATHS.ACHIEVEMENTS.BASE,
        moduleCode: 'achievements_hrd',
        fields: FIELD_GROUPS.HRD,
        siblings: [ROUTE_PATHS.ACHIEVEMENTS.HRD],
    },
]
