/**
 * All Masters Routes Configuration
 *
 * Contains all route configurations for the "All Masters" section.
 * Groups mirror the Form Management order:
 * Basic Masters, About KVK, Achievements, Projects, Performance Indicators, Miscellaneous.
 */

import { ENTITY_PATHS } from '../../constants/entityConstants'
import { FIELD_GROUPS, FIELD_NAMES } from '../../constants/fieldNames'
import { MASTER_SIBLING_GROUPS } from '../masterSiblingGroups'
import { RouteConfig } from './types'

// Form-aligned master group labels + landing paths (used for breadcrumbs and
// sidebar group highlighting).
const GROUP = {
    BASIC: { label: 'Basic Masters', path: '/all-master/basic' },
    ABOUT_KVK: { label: 'About KVK Master', path: '/all-master/about-kvk' },
    ACHIEVEMENTS: { label: 'Achievements Master', path: '/all-master/achievements' },
    PROJECTS: { label: 'Projects Master', path: '/all-master/projects' },
    PERFORMANCE: { label: 'Performance Indicators Master', path: '/all-master/performance' },
    MISCELLANEOUS: { label: 'Miscellaneous Master', path: '/all-master/miscellaneous' },
    OTHERS: { label: 'Others Master', path: '/all-master/others' },
} as const

export const allMastersRoutes: RouteConfig[] = [
    // Basic Masters
    {
        path: ENTITY_PATHS.ZONES,
        title: 'Zone Master',
        category: 'All Masters',
        subcategory: GROUP.BASIC.label,
        parent: '/all-master',
        subcategoryPath: GROUP.BASIC.path,
        siblings: MASTER_SIBLING_GROUPS.BASIC_MASTERS,
        fields: FIELD_GROUPS.ZONE_MASTER,
        defaultSortFields: [FIELD_NAMES.ZONE_NAME],
        moduleCode: 'all_masters_zone_master',
    },
    {
        path: ENTITY_PATHS.STATES,
        title: 'State Master',
        category: 'All Masters',
        subcategory: GROUP.BASIC.label,
        parent: '/all-master',
        subcategoryPath: GROUP.BASIC.path,
        siblings: MASTER_SIBLING_GROUPS.BASIC_MASTERS,
        fields: FIELD_GROUPS.STATE_MASTER,
        defaultSortFields: [FIELD_NAMES.ZONE_NAME, FIELD_NAMES.STATE_NAME],
        moduleCode: 'all_masters_states_master',
    },
    {
        path: ENTITY_PATHS.ORGANIZATIONS,
        title: 'Institute Master',
        category: 'All Masters',
        subcategory: GROUP.BASIC.label,
        parent: '/all-master',
        subcategoryPath: GROUP.BASIC.path,
        siblings: MASTER_SIBLING_GROUPS.BASIC_MASTERS,
        // Table shows only the unique institute name (one row per distinct name);
        // Zone/State/District are intentionally dropped. The add/edit form is
        // entityType-driven, so it still collects every field. Full-column copy
        // lives at /all-master-1/organizations (see allMasters1Routes).
        fields: [FIELD_NAMES.ORG_NAME],
        defaultSortFields: [FIELD_NAMES.ORG_NAME],
        uniqueByField: FIELD_NAMES.ORG_NAME,
        moduleCode: 'all_masters_organization_master',
    },
    {
        path: ENTITY_PATHS.UNIVERSITIES,
        title: 'Host Master',
        category: 'All Masters',
        subcategory: GROUP.BASIC.label,
        parent: '/all-master',
        subcategoryPath: GROUP.BASIC.path,
        siblings: MASTER_SIBLING_GROUPS.BASIC_MASTERS,
        // Table shows only the unique host name; the Institute column is dropped
        // here (kept in the form/backend and in the /all-master-1 copy).
        fields: [FIELD_NAMES.UNIVERSITY_NAME],
        defaultSortFields: [FIELD_NAMES.UNIVERSITY_NAME],
        uniqueByField: FIELD_NAMES.UNIVERSITY_NAME,
        moduleCode: 'all_masters_university_master',
    },
    {
        path: ENTITY_PATHS.KVK_MASTER,
        title: 'KVK Master',
        category: 'All Masters',
        subcategory: GROUP.BASIC.label,
        parent: '/all-master',
        subcategoryPath: GROUP.BASIC.path,
        siblings: MASTER_SIBLING_GROUPS.BASIC_MASTERS,
        fields: FIELD_GROUPS.VIEW_KVKS,
        defaultSortFields: [
            FIELD_NAMES.ZONE_NAME,
            FIELD_NAMES.STATE_NAME,
            FIELD_NAMES.DISTRICT_NAME,
            FIELD_NAMES.HOST_ORG,
            FIELD_NAMES.KVK_NAME,
        ],
        moduleCode: 'all_masters_kvks',
        canCreate: ['super_admin'],
    },
    {
        path: ENTITY_PATHS.DISTRICTS,
        title: 'District Master',
        category: 'All Masters',
        subcategory: GROUP.BASIC.label,
        parent: '/all-master',
        subcategoryPath: GROUP.BASIC.path,
        siblings: MASTER_SIBLING_GROUPS.BASIC_MASTERS,
        fields: FIELD_GROUPS.DISTRICT_MASTER,
        defaultSortFields: [
            FIELD_NAMES.ZONE_NAME,
            FIELD_NAMES.STATE_NAME,
            FIELD_NAMES.DISTRICT_NAME,
        ],
        moduleCode: 'all_masters_districts_master',
    },
    {
        path: ENTITY_PATHS.SEASON,
        title: 'Season Master',
        category: 'All Masters',
        subcategory: GROUP.OTHERS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.OTHERS.path,
        siblings: MASTER_SIBLING_GROUPS.CALENDAR_CONTEXT_MASTERS,
        fields: FIELD_GROUPS.SEASON_MASTER,
        moduleCode: 'all_masters_season_master',
    },
    {
        path: ENTITY_PATHS.UNIT,
        title: 'Unit Master',
        category: 'All Masters',
        subcategory: GROUP.OTHERS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.OTHERS.path,
        siblings: MASTER_SIBLING_GROUPS.CALENDAR_CONTEXT_MASTERS,
        fields: FIELD_GROUPS.UNIT_MASTER,
        moduleCode: 'all_masters_unit_master',
    },
    {
        path: ENTITY_PATHS.CROP_TYPE,
        title: 'Crop Type Master',
        category: 'All Masters',
        subcategory: GROUP.OTHERS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.OTHERS.path,
        siblings: MASTER_SIBLING_GROUPS.CALENDAR_CONTEXT_MASTERS,
        fields: FIELD_GROUPS.CROP_TYPE_MASTER,
        moduleCode: 'all_masters_crop_type_master',
    },

    // About KVK — Employee Masters
    {
        path: ENTITY_PATHS.STAFF_CATEGORY,
        title: 'Staff Category Master',
        category: 'All Masters',
        subcategory: GROUP.ABOUT_KVK.label,
        parent: '/all-master',
        subcategoryPath: GROUP.ABOUT_KVK.path,
        siblings: MASTER_SIBLING_GROUPS.EMPLOYEE_MASTERS,
        fields: FIELD_GROUPS.STAFF_CATEGORY_MASTER,
        moduleCode: 'all_masters_staff_category_master',
    },
    {
        path: ENTITY_PATHS.JOB_TYPE,
        title: 'Job Type Master',
        category: 'All Masters',
        subcategory: GROUP.ABOUT_KVK.label,
        parent: '/all-master',
        subcategoryPath: GROUP.ABOUT_KVK.path,
        siblings: MASTER_SIBLING_GROUPS.EMPLOYEE_MASTERS,
        fields: FIELD_GROUPS.JOB_TYPE_MASTER,
        moduleCode: 'all_masters_job_type_master',
    },
    {
        path: ENTITY_PATHS.BANK_ACCOUNT_TYPE,
        title: 'Bank Account Type Master',
        category: 'All Masters',
        subcategory: GROUP.ABOUT_KVK.label,
        parent: '/all-master',
        subcategoryPath: GROUP.ABOUT_KVK.path,
        siblings: MASTER_SIBLING_GROUPS.BANK_MASTERS,
        fields: FIELD_GROUPS.BANK_ACCOUNT_TYPE_MASTER,
        moduleCode: 'all_masters_bank_account_type_master',
    },
    {
        path: ENTITY_PATHS.PAY_LEVEL,
        title: 'Pay Level Master',
        category: 'All Masters',
        subcategory: GROUP.ABOUT_KVK.label,
        parent: '/all-master',
        subcategoryPath: GROUP.ABOUT_KVK.path,
        siblings: MASTER_SIBLING_GROUPS.EMPLOYEE_MASTERS,
        fields: FIELD_GROUPS.PAY_LEVEL_MASTER,
        moduleCode: 'all_masters_pay_level_master',
    },
    {
        path: ENTITY_PATHS.PAY_SCALE,
        title: 'Pay Scale Master',
        category: 'All Masters',
        subcategory: GROUP.ABOUT_KVK.label,
        parent: '/all-master',
        subcategoryPath: GROUP.ABOUT_KVK.path,
        siblings: MASTER_SIBLING_GROUPS.EMPLOYEE_MASTERS,
        fields: FIELD_GROUPS.PAY_SCALE_MASTER,
        moduleCode: 'all_masters_pay_scale_master',
    },
    {
        path: ENTITY_PATHS.FUNDING_SOURCE,
        title: 'Funding Source Master',
        category: 'All Masters',
        subcategory: GROUP.OTHERS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.OTHERS.path,
        siblings: MASTER_SIBLING_GROUPS.FUNDING_SOURCE_MASTERS,
        fields: FIELD_GROUPS.FUNDING_SOURCE_MASTER,
        moduleCode: 'all_masters_asset_funding_source_master',
    },
    {
        path: ENTITY_PATHS.VEHICLE_TYPE,
        title: 'Vehicle Type Master',
        category: 'All Masters',
        subcategory: GROUP.ABOUT_KVK.label,
        parent: '/all-master',
        subcategoryPath: GROUP.ABOUT_KVK.path,
        siblings: MASTER_SIBLING_GROUPS.ASSET_EQUIPMENT_MASTERS,
        fields: FIELD_GROUPS.EQUIPMENT_TYPE_MASTER,
        moduleCode: 'all_masters_equipment_type_master',
    },
    {
        path: ENTITY_PATHS.EQUIPMENT_TYPE,
        title: 'Equipment Type Master',
        category: 'All Masters',
        subcategory: GROUP.ABOUT_KVK.label,
        parent: '/all-master',
        subcategoryPath: GROUP.ABOUT_KVK.path,
        siblings: MASTER_SIBLING_GROUPS.ASSET_EQUIPMENT_MASTERS,
        fields: FIELD_GROUPS.EQUIPMENT_TYPE_MASTER,
        moduleCode: 'all_masters_equipment_type_master',
    },
    {
        path: ENTITY_PATHS.EQUIPMENT_MASTER,
        title: 'Equipment Master',
        category: 'All Masters',
        subcategory: GROUP.ABOUT_KVK.label,
        parent: '/all-master',
        subcategoryPath: GROUP.ABOUT_KVK.path,
        siblings: MASTER_SIBLING_GROUPS.ASSET_EQUIPMENT_MASTERS,
        fields: FIELD_GROUPS.EQUIPMENT_MASTER_MASTER,
        defaultSortFields: [FIELD_NAMES.EQUIPMENT_TYPE_NAME, FIELD_NAMES.NAME],
        moduleCode: 'all_masters_equipment_master',
    },
    {
        path: ENTITY_PATHS.DISCIPLINE,
        title: 'Discipline Master',
        category: 'All Masters',
        subcategory: GROUP.ABOUT_KVK.label,
        parent: '/all-master',
        subcategoryPath: GROUP.ABOUT_KVK.path,
        siblings: MASTER_SIBLING_GROUPS.EMPLOYEE_MASTERS,
        fields: FIELD_GROUPS.DISCIPLINE_MASTER,
        moduleCode: 'all_masters_discipline_master',
    },
    {
        path: ENTITY_PATHS.SANCTIONED_POST,
        title: 'Sanctioned Post Master',
        category: 'All Masters',
        subcategory: GROUP.ABOUT_KVK.label,
        parent: '/all-master',
        subcategoryPath: GROUP.ABOUT_KVK.path,
        siblings: MASTER_SIBLING_GROUPS.EMPLOYEE_MASTERS,
        fields: FIELD_GROUPS.SANCTIONED_POST_MASTER,
        moduleCode: 'all_masters_sanctioned_post_master',
    },
    {
        path: ENTITY_PATHS.INFRASTRUCTURE_MASTER,
        title: 'Infrastructure',
        category: 'All Masters',
        subcategory: GROUP.ABOUT_KVK.label,
        parent: '/all-master',
        subcategoryPath: GROUP.ABOUT_KVK.path,
        siblings: MASTER_SIBLING_GROUPS.INFRASTRUCTURE_LAND_MASTERS,
        fields: FIELD_GROUPS.TRAINING_CLIENTELE_MASTER,
        moduleCode: 'all_masters_infrastructure_master',
    },
    {
        path: ENTITY_PATHS.LAND_ITEM_MASTER,
        title: 'Land Item Master',
        category: 'All Masters',
        subcategory: GROUP.ABOUT_KVK.label,
        parent: '/all-master',
        subcategoryPath: GROUP.ABOUT_KVK.path,
        siblings: MASTER_SIBLING_GROUPS.INFRASTRUCTURE_LAND_MASTERS,
        fields: FIELD_GROUPS.LAND_ITEM_MASTER,
        moduleCode: 'all_masters_infrastructure_master',
    },
    {
        path: ENTITY_PATHS.VEHICLE_PRESENT_STATUS,
        title: 'Asset Status Master',
        category: 'All Masters',
        subcategory: GROUP.ABOUT_KVK.label,
        parent: '/all-master',
        subcategoryPath: GROUP.ABOUT_KVK.path,
        siblings: MASTER_SIBLING_GROUPS.ASSET_EQUIPMENT_MASTERS,
        fields: FIELD_GROUPS.VEHICLE_PRESENT_STATUS_MASTER,
        moduleCode: 'all_masters_vehicle_present_status_master',
    },
    {
        path: ENTITY_PATHS.EQUIPMENT_PRESENT_STATUS,
        title: 'Equipment Present Status',
        category: 'All Masters',
        subcategory: GROUP.ABOUT_KVK.label,
        parent: '/all-master',
        subcategoryPath: GROUP.ABOUT_KVK.path,
        siblings: MASTER_SIBLING_GROUPS.ASSET_EQUIPMENT_MASTERS,
        fields: FIELD_GROUPS.EQUIPMENT_PRESENT_STATUS_MASTER,
        moduleCode: 'all_masters_equipment_present_status_master',
    },

    // Achievements — OFT Masters
    {
        path: ENTITY_PATHS.OFT_SUBJECT,
        title: 'Subject Master',
        category: 'All Masters',
        subcategory: GROUP.ACHIEVEMENTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.ACHIEVEMENTS.path,
        siblings: MASTER_SIBLING_GROUPS.OFT_MASTERS,
        fields: FIELD_GROUPS.OFT_SUBJECT_MASTER,
        moduleCode: 'all_masters_oft_master',
    },
    {
        path: ENTITY_PATHS.OFT_THEMATIC_AREA,
        title: 'OFT Thematic Area Master',
        category: 'All Masters',
        subcategory: GROUP.ACHIEVEMENTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.ACHIEVEMENTS.path,
        siblings: MASTER_SIBLING_GROUPS.OFT_MASTERS,
        fields: FIELD_GROUPS.OFT_THEMATIC_AREA_MASTER,
        defaultSortFields: [FIELD_NAMES.SUBJECT_NAME, FIELD_NAMES.THEMATIC_AREA_NAME],
        moduleCode: 'all_masters_oft_master',
    },

    // Achievements — FLD Masters
    {
        path: ENTITY_PATHS.FLD_SECTOR,
        title: 'Sector Master',
        category: 'All Masters',
        subcategory: GROUP.ACHIEVEMENTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.ACHIEVEMENTS.path,
        siblings: MASTER_SIBLING_GROUPS.FLD_MASTERS,
        fields: FIELD_GROUPS.FLD_SECTOR_MASTER,
        moduleCode: 'all_masters_fld_master',
    },
    {
        path: ENTITY_PATHS.FLD_THEMATIC_AREA,
        title: 'FLD Thematic Area Master',
        category: 'All Masters',
        subcategory: GROUP.ACHIEVEMENTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.ACHIEVEMENTS.path,
        siblings: MASTER_SIBLING_GROUPS.FLD_MASTERS,
        fields: FIELD_GROUPS.FLD_THEMATIC_AREA_MASTER,
        defaultSortFields: [FIELD_NAMES.SECTOR_NAME, FIELD_NAMES.THEMATIC_AREA_NAME],
        moduleCode: 'all_masters_fld_master',
    },
    {
        path: ENTITY_PATHS.FLD_CATEGORY,
        title: 'Category Master',
        category: 'All Masters',
        subcategory: GROUP.ACHIEVEMENTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.ACHIEVEMENTS.path,
        siblings: MASTER_SIBLING_GROUPS.FLD_MASTERS,
        fields: FIELD_GROUPS.FLD_CATEGORY_MASTER,
        defaultSortFields: [FIELD_NAMES.SECTOR_NAME, FIELD_NAMES.CATEGORY_NAME],
        moduleCode: 'all_masters_fld_master',
    },
    {
        path: ENTITY_PATHS.FLD_SUBCATEGORY,
        title: 'Sub-category Master',
        category: 'All Masters',
        subcategory: GROUP.ACHIEVEMENTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.ACHIEVEMENTS.path,
        siblings: MASTER_SIBLING_GROUPS.FLD_MASTERS,
        fields: FIELD_GROUPS.FLD_SUBCATEGORY_MASTER,
        defaultSortFields: [FIELD_NAMES.SECTOR_NAME, FIELD_NAMES.CATEGORY_NAME, FIELD_NAMES.SUB_CATEGORY_NAME],
        moduleCode: 'all_masters_fld_master',
    },
    {
        path: ENTITY_PATHS.FLD_CROP,
        title: 'Crop Master',
        category: 'All Masters',
        subcategory: GROUP.ACHIEVEMENTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.ACHIEVEMENTS.path,
        siblings: MASTER_SIBLING_GROUPS.FLD_MASTERS,
        fields: FIELD_GROUPS.FLD_CROP_MASTER,
        defaultSortFields: [FIELD_NAMES.CATEGORY_NAME, FIELD_NAMES.SUB_CATEGORY_NAME, FIELD_NAMES.CROP_NAME],
        moduleCode: 'all_masters_fld_master',
    },
    {
        path: ENTITY_PATHS.FLD_ACTIVITY,
        title: 'Activity Master',
        category: 'All Masters',
        subcategory: GROUP.ACHIEVEMENTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.ACHIEVEMENTS.path,
        siblings: MASTER_SIBLING_GROUPS.FLD_MASTERS,
        fields: FIELD_GROUPS.FLD_ACTIVITY_MASTER,
        moduleCode: 'all_masters_fld_master',
    },

    // Achievements — Training Masters
    {
        path: ENTITY_PATHS.TRAINING_TYPE,
        title: 'Training Type Master',
        category: 'All Masters',
        subcategory: GROUP.ACHIEVEMENTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.ACHIEVEMENTS.path,
        siblings: MASTER_SIBLING_GROUPS.TRAINING_BASIC_MASTERS,
        fields: FIELD_GROUPS.TRAINING_TYPE_MASTER,
        moduleCode: 'all_masters_training_master',
    },
    {
        path: ENTITY_PATHS.TRAINING_AREA,
        title: 'Training Area Master',
        category: 'All Masters',
        subcategory: GROUP.ACHIEVEMENTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.ACHIEVEMENTS.path,
        siblings: MASTER_SIBLING_GROUPS.TRAINING_BASIC_MASTERS,
        fields: FIELD_GROUPS.TRAINING_AREA_MASTER,
        moduleCode: 'all_masters_training_master',
    },
    {
        path: ENTITY_PATHS.TRAINING_THEMATIC,
        title: 'Training Thematic Area Master',
        category: 'All Masters',
        subcategory: GROUP.ACHIEVEMENTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.ACHIEVEMENTS.path,
        siblings: MASTER_SIBLING_GROUPS.TRAINING_BASIC_MASTERS,
        fields: FIELD_GROUPS.TRAINING_THEMATIC_AREA_MASTER,
        moduleCode: 'all_masters_training_master',
    },
    {
        path: ENTITY_PATHS.TRAINING_CLIENTELE,
        title: 'Training Clientele Master',
        category: 'All Masters',
        subcategory: GROUP.ACHIEVEMENTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.ACHIEVEMENTS.path,
        siblings: MASTER_SIBLING_GROUPS.TRAINING_BASIC_MASTERS,
        fields: FIELD_GROUPS.TRAINING_CLIENTELE_MASTER,
        moduleCode: 'all_masters_training_master',
    },

    // Achievements — Extension Activities
    {
        path: ENTITY_PATHS.EXTENSION_ACTIVITY,
        title: 'Extension Activity Master',
        category: 'All Masters',
        subcategory: GROUP.ACHIEVEMENTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.ACHIEVEMENTS.path,
        siblings: MASTER_SIBLING_GROUPS.TRAINING_EXTENSION_MASTERS,
        fields: FIELD_GROUPS.TRAINING_CLIENTELE_MASTER,
        moduleCode: 'all_masters_extension_activity_master',
    },
    {
        path: ENTITY_PATHS.OTHER_EXTENSION_ACTIVITY,
        title: 'Other Extension Activity Master',
        category: 'All Masters',
        subcategory: GROUP.ACHIEVEMENTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.ACHIEVEMENTS.path,
        siblings: MASTER_SIBLING_GROUPS.TRAINING_EXTENSION_MASTERS,
        fields: FIELD_GROUPS.TRAINING_CLIENTELE_MASTER,
        moduleCode: 'all_masters_other_extension_activity_master',
    },

    // Achievements — Production of Seed, Planting Materials and Bio Products
    {
        path: ENTITY_PATHS.PRODUCT_CATEGORY,
        title: 'Product Category Master',
        category: 'All Masters',
        subcategory: GROUP.ACHIEVEMENTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.ACHIEVEMENTS.path,
        siblings: MASTER_SIBLING_GROUPS.PRODUCT_MASTERS,
        fields: FIELD_GROUPS.PRODUCT_CATEGORY_MASTER,
        moduleCode: 'all_masters_products_master',
    },
    {
        path: ENTITY_PATHS.PRODUCT_TYPE,
        title: 'Product Type Master',
        category: 'All Masters',
        subcategory: GROUP.ACHIEVEMENTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.ACHIEVEMENTS.path,
        siblings: MASTER_SIBLING_GROUPS.PRODUCT_MASTERS,
        fields: FIELD_GROUPS.PRODUCT_TYPE_MASTER,
        moduleCode: 'all_masters_products_master',
    },
    {
        path: ENTITY_PATHS.PRODUCT,
        title: 'Products Master',
        category: 'All Masters',
        subcategory: GROUP.ACHIEVEMENTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.ACHIEVEMENTS.path,
        siblings: MASTER_SIBLING_GROUPS.PRODUCT_MASTERS,
        fields: FIELD_GROUPS.PRODUCT_MASTER,
        moduleCode: 'all_masters_products_master',
    },

    // Achievements — Soil & Celebration Masters
    {
        path: ENTITY_PATHS.SOIL_WATER_ANALYSIS,
        title: 'Soil Water',
        category: 'All Masters',
        subcategory: GROUP.ACHIEVEMENTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.ACHIEVEMENTS.path,
        siblings: MASTER_SIBLING_GROUPS.SOIL_CELEBRATION_MASTERS,
        fields: FIELD_GROUPS.SOIL_WATER_ANALYSIS_MASTER,
        moduleCode: 'all_masters_soil_water_analysis_master',
    },
    {
        path: ENTITY_PATHS.IMPORTANT_DAY,
        title: 'Important Day Master',
        category: 'All Masters',
        subcategory: GROUP.ACHIEVEMENTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.ACHIEVEMENTS.path,
        siblings: MASTER_SIBLING_GROUPS.SOIL_CELEBRATION_MASTERS,
        fields: FIELD_GROUPS.IMPORTANT_DAY_MASTER,
        moduleCode: 'all_masters_events_master',
    },

    // Achievements — Publications
    {
        path: ENTITY_PATHS.PUBLICATION_ITEM,
        title: 'Publication Items Master',
        category: 'All Masters',
        subcategory: GROUP.ACHIEVEMENTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.ACHIEVEMENTS.path,
        siblings: MASTER_SIBLING_GROUPS.PUBLICATION_MASTERS,
        fields: FIELD_GROUPS.PUBLICATION_ITEM_MASTER,
        moduleCode: 'all_masters_publication_master',
    },

    // Projects — CFLD Masters
    {
        path: ENTITY_PATHS.CFLD_CROP,
        title: 'CFLD Crop Master',
        category: 'All Masters',
        subcategory: GROUP.PROJECTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.PROJECTS.path,
        siblings: MASTER_SIBLING_GROUPS.CFLD_MASTERS,
        fields: FIELD_GROUPS.CFLD_CROP_MASTER,
        moduleCode: 'all_masters_cfld_master',
    },
    {
        path: ENTITY_PATHS.BUDGET_ITEM_MASTER,
        title: 'CFLD Budget Item Master',
        category: 'All Masters',
        subcategory: GROUP.PROJECTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.PROJECTS.path,
        siblings: MASTER_SIBLING_GROUPS.CFLD_MASTERS,
        fields: FIELD_GROUPS.BUDGET_ITEM_MASTER,
        moduleCode: 'all_masters_budget_item_master',
    },

    // Projects — Climate Resilient Agriculture
    {
        path: ENTITY_PATHS.CRA_CROPPING_SYSTEM,
        title: 'Cropping System Master',
        category: 'All Masters',
        subcategory: GROUP.PROJECTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.PROJECTS.path,
        siblings: MASTER_SIBLING_GROUPS.CRA_MASTERS,
        fields: FIELD_GROUPS.CRA_CROPPING_SYSTEM_MASTER,
        moduleCode: 'all_masters_climate_master',
    },
    {
        path: ENTITY_PATHS.CRA_FARMING_SYSTEM,
        title: 'Farming System Master',
        category: 'All Masters',
        subcategory: GROUP.PROJECTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.PROJECTS.path,
        siblings: MASTER_SIBLING_GROUPS.CRA_MASTERS,
        fields: FIELD_GROUPS.CRA_FARMING_SYSTEM_MASTER,
        moduleCode: 'all_masters_climate_master',
    },

    // Projects — ARYA
    {
        path: ENTITY_PATHS.ARYA_ENTERPRISE,
        title: 'ARYA Enterprise Master',
        category: 'All Masters',
        subcategory: GROUP.PROJECTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.PROJECTS.path,
        siblings: MASTER_SIBLING_GROUPS.ARYA_MASTERS,
        fields: FIELD_GROUPS.ARYA_ENTERPRISE_MASTER,
        moduleCode: 'all_masters_arya_master',
    },

    // Projects — TSP/SCSP
    {
        path: ENTITY_PATHS.TSP_SCSP_TYPE,
        title: 'TSP/SCSP Type Master',
        category: 'All Masters',
        subcategory: GROUP.PROJECTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.PROJECTS.path,
        siblings: MASTER_SIBLING_GROUPS.TSP_SCSP_MASTERS,
        fields: FIELD_GROUPS.CROP_TYPE_MASTER,
        moduleCode: 'all_masters_tsp_scsp_master',
    },
    {
        path: ENTITY_PATHS.TSP_SCSP_ACTIVITY,
        title: 'TSP/SCSP Activity Master',
        category: 'All Masters',
        subcategory: GROUP.PROJECTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.PROJECTS.path,
        siblings: MASTER_SIBLING_GROUPS.TSP_SCSP_MASTERS,
        fields: FIELD_GROUPS.FLD_ACTIVITY_MASTER,
        moduleCode: 'all_masters_tsp_scsp_master',
    },

    // Projects — Natural Farming
    {
        path: ENTITY_PATHS.NATURAL_FARMING_ACTIVITY,
        title: 'Natural Farming Activity Master',
        category: 'All Masters',
        subcategory: GROUP.PROJECTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.PROJECTS.path,
        siblings: MASTER_SIBLING_GROUPS.NATURAL_FARMING_MASTERS,
        fields: [FIELD_NAMES.ACTIVITY_NAME] as const,
        moduleCode: 'all_masters_natural_farming_master',
    },
    {
        path: ENTITY_PATHS.NATURAL_FARMING_SOIL_PARAMETER,
        title: 'Natural Farming Soil Parameter Master',
        category: 'All Masters',
        subcategory: GROUP.PROJECTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.PROJECTS.path,
        siblings: MASTER_SIBLING_GROUPS.NATURAL_FARMING_MASTERS,
        fields: [FIELD_NAMES.TYPE] as const,
        moduleCode: 'all_masters_natural_farming_master',
    },

    // Projects — Agri Drone
    {
        path: ENTITY_PATHS.AGRI_DRONE_DEMONSTRATIONS_ON,
        title: 'Agri-Drone Demonstrations On Master',
        category: 'All Masters',
        subcategory: GROUP.PROJECTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.PROJECTS.path,
        siblings: MASTER_SIBLING_GROUPS.AGRI_DRONE_MASTERS,
        fields: [FIELD_NAMES.DEMONSTRATIONS_ON] as const,
        moduleCode: 'all_masters_agri_drone_master',
    },

    // Projects — NARI Masters
    {
        path: ENTITY_PATHS.NARI_ACTIVITY,
        title: 'NARI Activity Master',
        category: 'All Masters',
        subcategory: GROUP.PROJECTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.PROJECTS.path,
        siblings: MASTER_SIBLING_GROUPS.NARI_MASTERS,
        fields: FIELD_GROUPS.FLD_ACTIVITY_MASTER,
        moduleCode: 'all_masters_nari_activity_master',
    },
    {
        path: ENTITY_PATHS.NARI_CROP_CATEGORY,
        title: 'NARI Crop Category Master',
        category: 'All Masters',
        subcategory: GROUP.PROJECTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.PROJECTS.path,
        siblings: MASTER_SIBLING_GROUPS.NARI_MASTERS,
        fields: [FIELD_NAMES.NAME] as const,
        moduleCode: 'all_masters_nari_activity_master',
    },
    {
        path: ENTITY_PATHS.NARI_NUTRITION_GARDEN_TYPE,
        title: 'NARI Nutrition Garden Type Master',
        category: 'All Masters',
        subcategory: GROUP.PROJECTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.PROJECTS.path,
        siblings: MASTER_SIBLING_GROUPS.NARI_MASTERS,
        fields: FIELD_GROUPS.TRAINING_CLIENTELE_MASTER,
        moduleCode: 'all_masters_nari_garden_type_master',
    },

    // Projects — NICRA Masters
    {
        path: ENTITY_PATHS.NICRA_CATEGORY,
        title: 'NICRA Category Master',
        category: 'All Masters',
        subcategory: GROUP.PROJECTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.PROJECTS.path,
        siblings: MASTER_SIBLING_GROUPS.NICRA_MASTERS,
        fields: FIELD_GROUPS.NICRA_CATEGORY_MASTER,
        moduleCode: 'all_masters_nicra_master',
    },
    {
        path: ENTITY_PATHS.NICRA_SUB_CATEGORY,
        title: 'NICRA Sub-category Master',
        category: 'All Masters',
        subcategory: GROUP.PROJECTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.PROJECTS.path,
        siblings: MASTER_SIBLING_GROUPS.NICRA_MASTERS,
        fields: FIELD_GROUPS.NICRA_SUB_CATEGORY_MASTER,
        defaultSortFields: [FIELD_NAMES.CATEGORY_NAME, FIELD_NAMES.SUB_CATEGORY_NAME],
        moduleCode: 'all_masters_nicra_master',
    },
    {
        path: ENTITY_PATHS.NICRA_SEED_BANK_FODDER_BANK,
        title: 'NICRA Seed/Fodder Bank Master',
        category: 'All Masters',
        subcategory: GROUP.PROJECTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.PROJECTS.path,
        siblings: MASTER_SIBLING_GROUPS.NICRA_MASTERS,
        fields: FIELD_GROUPS.NICRA_SEED_BANK_FODDER_BANK_MASTER,
        moduleCode: 'all_masters_nicra_master',
    },
    {
        path: ENTITY_PATHS.NICRA_DIGNITARY_TYPE,
        title: 'NICRA Dignitary Type Master',
        category: 'All Masters',
        subcategory: GROUP.PROJECTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.PROJECTS.path,
        siblings: MASTER_SIBLING_GROUPS.NICRA_MASTERS,
        fields: [FIELD_NAMES.TYPE] as const,
        moduleCode: 'all_masters_nicra_master',
    },
    {
        path: ENTITY_PATHS.NICRA_PI_TYPE,
        title: 'NICRA PI/CO-PI Type Master',
        category: 'All Masters',
        subcategory: GROUP.PROJECTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.PROJECTS.path,
        siblings: MASTER_SIBLING_GROUPS.NICRA_MASTERS,
        fields: [FIELD_NAMES.TYPE] as const,
        moduleCode: 'all_masters_nicra_master',
    },

    // Projects — Project wise Budget Masters
    {
        path: ENTITY_PATHS.FINANCIAL_PROJECT,
        title: 'Financial Project Master',
        category: 'All Masters',
        subcategory: GROUP.PROJECTS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.PROJECTS.path,
        siblings: MASTER_SIBLING_GROUPS.PROJECT_BUDGET_MASTERS,
        fields: FIELD_GROUPS.FINANCIAL_PROJECT_MASTER,
        defaultSortFields: [FIELD_NAMES.FUNDING_AGENCY_NAME, FIELD_NAMES.PROJECT_NAME],
        moduleCode: 'all_masters_financial_project_master',
    },

    // Performance Indicators
    {
        path: ENTITY_PATHS.IMPACT_SPECIFIC_AREA,
        title: 'Impact Areas',
        category: 'All Masters',
        subcategory: GROUP.PERFORMANCE.label,
        parent: '/all-master',
        subcategoryPath: GROUP.PERFORMANCE.path,
        siblings: MASTER_SIBLING_GROUPS.PERFORMANCE_MASTERS,
        fields: FIELD_GROUPS.IMPACT_SPECIFIC_AREA_MASTER,
        moduleCode: 'all_masters_impact_area_master',
    },
    {
        path: ENTITY_PATHS.ENTERPRISE_TYPE,
        title: 'Enterprises',
        category: 'All Masters',
        subcategory: GROUP.PERFORMANCE.label,
        parent: '/all-master',
        subcategoryPath: GROUP.PERFORMANCE.path,
        siblings: MASTER_SIBLING_GROUPS.PERFORMANCE_MASTERS,
        fields: FIELD_GROUPS.ENTERPRISE_TYPE_MASTER,
        moduleCode: 'all_masters_enterprise_type_master',
    },
    {
        path: ENTITY_PATHS.ACCOUNT_TYPE,
        title: 'Account Types',
        category: 'All Masters',
        subcategory: GROUP.PERFORMANCE.label,
        parent: '/all-master',
        subcategoryPath: GROUP.PERFORMANCE.path,
        siblings: MASTER_SIBLING_GROUPS.PERFORMANCE_MASTERS,
        fields: FIELD_GROUPS.ACCOUNT_TYPE_MASTER,
        moduleCode: 'all_masters_account_type_master',
    },
    {
        path: ENTITY_PATHS.PROGRAMME_TYPE,
        title: 'Programs',
        category: 'All Masters',
        subcategory: GROUP.PERFORMANCE.label,
        parent: '/all-master',
        subcategoryPath: GROUP.PERFORMANCE.path,
        siblings: MASTER_SIBLING_GROUPS.PERFORMANCE_MASTERS,
        fields: FIELD_GROUPS.PROGRAMME_TYPE_MASTER,
        moduleCode: 'all_masters_programme_type_master',
    },

    // Miscellaneous
    {
        path: ENTITY_PATHS.PPV_FRA_TRAINING_TYPE,
        title: 'PPV & FRA',
        category: 'All Masters',
        subcategory: GROUP.MISCELLANEOUS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.MISCELLANEOUS.path,
        siblings: MASTER_SIBLING_GROUPS.MISC_MASTERS,
        fields: FIELD_GROUPS.PPV_FRA_TRAINING_TYPE_MASTER,
        moduleCode: 'all_masters_ppv_fra_training_type_master',
    },
    {
        path: ENTITY_PATHS.DIGNITARY_TYPE,
        title: 'VIP Dignitaries',
        category: 'All Masters',
        subcategory: GROUP.MISCELLANEOUS.label,
        parent: '/all-master',
        subcategoryPath: GROUP.MISCELLANEOUS.path,
        siblings: MASTER_SIBLING_GROUPS.MISC_MASTERS,
        fields: [FIELD_NAMES.NAME] as const,
        moduleCode: 'all_masters_dignitary_type_master',
    },
]

/**
 * Backup copy of the Basic Masters set, mounted at /all-master-1.
 *
 * This is a frozen snapshot of the ORIGINAL Basic Masters behaviour (full
 * columns, no dedupe) kept so the pre-change Institute/Host tables stay
 * reachable. It is intentionally NOT linked in the sidebar — only reachable by
 * typing the URL. Entity-type/data resolution normalizes /all-master-1 back to
 * /all-master (see getEntityTypeFromPathMap), so it reads the same data.
 */
export const allMasters1Routes: RouteConfig[] = [
    {
        path: '/all-master-1/zones',
        title: 'Zone Master',
        category: 'All Masters',
        subcategory: 'Basic Masters',
        parent: '/all-master-1',
        subcategoryPath: '/all-master-1/basic',
        siblings: MASTER_SIBLING_GROUPS.BASIC_MASTERS_1,
        fields: FIELD_GROUPS.ZONE_MASTER,
        defaultSortFields: [FIELD_NAMES.ZONE_NAME],
        moduleCode: 'all_masters_zone_master',
    },
    {
        path: '/all-master-1/states',
        title: 'State Master',
        category: 'All Masters',
        subcategory: 'Basic Masters',
        parent: '/all-master-1',
        subcategoryPath: '/all-master-1/basic',
        siblings: MASTER_SIBLING_GROUPS.BASIC_MASTERS_1,
        fields: FIELD_GROUPS.STATE_MASTER,
        defaultSortFields: [FIELD_NAMES.ZONE_NAME, FIELD_NAMES.STATE_NAME],
        moduleCode: 'all_masters_states_master',
    },
    {
        path: '/all-master-1/districts',
        title: 'District Master',
        category: 'All Masters',
        subcategory: 'Basic Masters',
        parent: '/all-master-1',
        subcategoryPath: '/all-master-1/basic',
        siblings: MASTER_SIBLING_GROUPS.BASIC_MASTERS_1,
        fields: FIELD_GROUPS.DISTRICT_MASTER,
        defaultSortFields: [
            FIELD_NAMES.ZONE_NAME,
            FIELD_NAMES.STATE_NAME,
            FIELD_NAMES.DISTRICT_NAME,
        ],
        moduleCode: 'all_masters_districts_master',
    },
    {
        path: '/all-master-1/organizations',
        title: 'Institute Master',
        category: 'All Masters',
        subcategory: 'Basic Masters',
        parent: '/all-master-1',
        subcategoryPath: '/all-master-1/basic',
        siblings: MASTER_SIBLING_GROUPS.BASIC_MASTERS_1,
        fields: FIELD_GROUPS.ORGANIZATION_MASTER,
        defaultSortFields: [
            FIELD_NAMES.ZONE_NAME,
            FIELD_NAMES.STATE_NAME,
            FIELD_NAMES.DISTRICT_NAME,
            FIELD_NAMES.ORG_NAME,
        ],
        moduleCode: 'all_masters_organization_master',
    },
    {
        path: '/all-master-1/universities',
        title: 'Host Master',
        category: 'All Masters',
        subcategory: 'Basic Masters',
        parent: '/all-master-1',
        subcategoryPath: '/all-master-1/basic',
        siblings: MASTER_SIBLING_GROUPS.BASIC_MASTERS_1,
        fields: [
            FIELD_NAMES.ZONE_NAME,
            FIELD_NAMES.STATE_NAME,
            FIELD_NAMES.DISTRICT_NAME,
            FIELD_NAMES.ORGANIZATION_ORG_NAME,
            FIELD_NAMES.UNIVERSITY_NAME,
        ],
        defaultSortFields: [
            FIELD_NAMES.ZONE_NAME,
            FIELD_NAMES.STATE_NAME,
            FIELD_NAMES.DISTRICT_NAME,
            FIELD_NAMES.ORGANIZATION_ORG_NAME,
            FIELD_NAMES.UNIVERSITY_NAME,
        ],
        moduleCode: 'all_masters_university_master',
    },
    {
        path: '/all-master-1/kvks',
        title: 'KVK Master',
        category: 'All Masters',
        subcategory: 'Basic Masters',
        parent: '/all-master-1',
        subcategoryPath: '/all-master-1/basic',
        siblings: MASTER_SIBLING_GROUPS.BASIC_MASTERS_1,
        fields: FIELD_GROUPS.VIEW_KVKS,
        defaultSortFields: [
            FIELD_NAMES.ZONE_NAME,
            FIELD_NAMES.STATE_NAME,
            FIELD_NAMES.DISTRICT_NAME,
            FIELD_NAMES.HOST_ORG,
            FIELD_NAMES.KVK_NAME,
        ],
        moduleCode: 'all_masters_kvks',
        canCreate: ['super_admin'],
    },
]
