/**
 * All Masters Routes Configuration
 *
 * Contains all route configurations for the "All Masters" section.
 * These routes are organized by subcategories: Basic Masters, OFT & FLD Masters,
 * Training & Extension Masters, Production & Projects Masters, Publications Masters, and Other Masters.
 */

import { ENTITY_PATHS } from '../../constants/entityConstants'
import { FIELD_GROUPS, FIELD_NAMES } from '../../constants/fieldNames'
import { MASTER_SIBLING_GROUPS } from '../masterSiblingGroups'
import { RouteConfig } from './types'

export const allMastersRoutes: RouteConfig[] = [
    // Basic Masters
    {
        path: ENTITY_PATHS.ZONES,
        title: 'Zone Master',
        category: 'All Masters',
        subcategory: 'Basic Masters',
        parent: '/all-master',
        subcategoryPath: '/all-master/basic',
        siblings: MASTER_SIBLING_GROUPS.BASIC_MASTERS,
        fields: FIELD_GROUPS.ZONE_MASTER,
        moduleCode: 'all_masters_zone_master',
    },
    {
        path: ENTITY_PATHS.STATES,
        title: 'State Master',
        category: 'All Masters',
        subcategory: 'Basic Masters',
        parent: '/all-master',
        subcategoryPath: '/all-master/basic',
        siblings: MASTER_SIBLING_GROUPS.BASIC_MASTERS,
        fields: FIELD_GROUPS.STATE_MASTER,
        moduleCode: 'all_masters_states_master',
    },
    {
        path: ENTITY_PATHS.ORGANIZATIONS,
        title: 'Organization Master',
        category: 'All Masters',
        subcategory: 'Basic Masters',
        parent: '/all-master',
        subcategoryPath: '/all-master/basic',
        siblings: MASTER_SIBLING_GROUPS.BASIC_MASTERS,
        fields: FIELD_GROUPS.ORGANIZATION_MASTER,
        moduleCode: 'all_masters_organization_master',
    },
    {
        path: ENTITY_PATHS.UNIVERSITIES,
        title: 'University Master',
        category: 'All Masters',
        subcategory: 'Basic Masters',
        parent: '/all-master',
        subcategoryPath: '/all-master/basic',
        siblings: MASTER_SIBLING_GROUPS.BASIC_MASTERS,
        fields: FIELD_GROUPS.UNIVERSITY_MASTER,
        moduleCode: 'all_masters_university_master',
    },
    {
        path: ENTITY_PATHS.DISTRICTS,
        title: 'District Master',
        category: 'All Masters',
        subcategory: 'Basic Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.BASIC_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.BASIC_MASTERS,
        fields: FIELD_GROUPS.DISTRICT_MASTER,
        moduleCode: 'all_masters_districts_master',
    },

    // OFT Masters
    {
        path: ENTITY_PATHS.OFT_SUBJECT,
        title: 'Subject Master',
        category: 'All Masters',
        subcategory: 'OFT & FLD Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.OFT_FLD_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.OFT_MASTERS,
        fields: FIELD_GROUPS.OFT_SUBJECT_MASTER,
        moduleCode: 'all_masters_oft_master',
    },
    {
        path: ENTITY_PATHS.OFT_THEMATIC_AREA,
        title: 'OFT Thematic Area Master',
        category: 'All Masters',
        subcategory: 'OFT & FLD Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.OFT_FLD_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.OFT_MASTERS,
        fields: FIELD_GROUPS.OFT_THEMATIC_AREA_MASTER,
        moduleCode: 'all_masters_oft_master',
    },

    // FLD Masters
    {
        path: ENTITY_PATHS.FLD_SECTOR,
        title: 'Sector Master',
        category: 'All Masters',
        subcategory: 'OFT & FLD Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.OFT_FLD_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.FLD_MASTERS,
        fields: FIELD_GROUPS.FLD_SECTOR_MASTER,
        moduleCode: 'all_masters_fld_master',
    },
    {
        path: ENTITY_PATHS.FLD_THEMATIC_AREA,
        title: 'FLD Thematic Area Master',
        category: 'All Masters',
        subcategory: 'OFT & FLD Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.OFT_FLD_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.FLD_MASTERS,
        fields: FIELD_GROUPS.FLD_THEMATIC_AREA_MASTER,
        moduleCode: 'all_masters_fld_master',
    },
    {
        path: ENTITY_PATHS.FLD_CATEGORY,
        title: 'Category Master',
        category: 'All Masters',
        subcategory: 'OFT & FLD Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.OFT_FLD_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.FLD_MASTERS,
        fields: FIELD_GROUPS.FLD_CATEGORY_MASTER,
        moduleCode: 'all_masters_fld_master',
    },
    {
        path: ENTITY_PATHS.FLD_SUBCATEGORY,
        title: 'Sub-category Master',
        category: 'All Masters',
        subcategory: 'OFT & FLD Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.OFT_FLD_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.FLD_MASTERS,
        fields: FIELD_GROUPS.FLD_SUBCATEGORY_MASTER,
        moduleCode: 'all_masters_fld_master',
    },
    {
        path: ENTITY_PATHS.FLD_CROP,
        title: 'Crop Master',
        category: 'All Masters',
        subcategory: 'OFT & FLD Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.OFT_FLD_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.FLD_MASTERS,
        fields: FIELD_GROUPS.FLD_CROP_MASTER,
        moduleCode: 'all_masters_fld_master',
    },
    {
        path: ENTITY_PATHS.FLD_ACTIVITY,
        title: 'Activity Master',
        category: 'All Masters',
        subcategory: 'OFT & FLD Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.OFT_FLD_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.FLD_MASTERS,
        fields: FIELD_GROUPS.FLD_ACTIVITY_MASTER,
        moduleCode: 'all_masters_fld_master',
    },

    // CFLD Masters
    {
        path: ENTITY_PATHS.CFLD_CROP,
        title: 'CFLD Crop Master',
        category: 'All Masters',
        subcategory: 'OFT & FLD Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.OFT_FLD_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.CFLD_MASTERS,
        fields: FIELD_GROUPS.CFLD_CROP_MASTER,
        moduleCode: 'all_masters_cfld_master',
    },

    // Training Master
    {
        path: ENTITY_PATHS.TRAINING_TYPE,
        title: 'Training Type Master',
        category: 'All Masters',
        subcategory: 'Training & Extension Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.TRAINING_EXTENSION_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.TRAINING_BASIC_MASTERS,
        fields: FIELD_GROUPS.TRAINING_TYPE_MASTER,
        moduleCode: 'all_masters_training_master',
    },
    {
        path: ENTITY_PATHS.TRAINING_AREA,
        title: 'Training Area Master',
        category: 'All Masters',
        subcategory: 'Training & Extension Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.TRAINING_EXTENSION_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.TRAINING_BASIC_MASTERS,
        fields: FIELD_GROUPS.TRAINING_AREA_MASTER,
        moduleCode: 'all_masters_training_master',
    },
    {
        path: ENTITY_PATHS.TRAINING_THEMATIC,
        title: 'Training Thematic Area Master',
        category: 'All Masters',
        subcategory: 'Training & Extension Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.TRAINING_EXTENSION_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.TRAINING_BASIC_MASTERS,
        fields: FIELD_GROUPS.TRAINING_THEMATIC_AREA_MASTER,
        moduleCode: 'all_masters_training_master',
    },
    {
        path: ENTITY_PATHS.TRAINING_CLIENTELE,
        title: 'Training Clientele Master',
        category: 'All Masters',
        subcategory: 'Training & Extension Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.TRAINING_EXTENSION_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.TRAINING_BASIC_MASTERS,
        fields: FIELD_GROUPS.TRAINING_CLIENTELE_MASTER,
        moduleCode: 'all_masters_training_master',
    },
    {
        path: ENTITY_PATHS.FUNDING_SOURCE,
        title: 'Funding Source Master',
        category: 'All Masters',
        subcategory: 'Training & Extension Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.TRAINING_EXTENSION_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.TRAINING_BASIC_MASTERS,
        fields: FIELD_GROUPS.TRAINING_CLIENTELE_MASTER,
        moduleCode: 'all_masters_training_master',
    },

    // Extension & Events
    {
        path: ENTITY_PATHS.EXTENSION_ACTIVITY,
        title: 'Extension Activity Master',
        category: 'All Masters',
        subcategory: 'Training & Extension Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.TRAINING_EXTENSION_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.TRAINING_EXTENSION_MASTERS,
        fields: FIELD_GROUPS.TRAINING_CLIENTELE_MASTER,
        moduleCode: 'all_masters_extension_activity_master',
    },
    {
        path: ENTITY_PATHS.OTHER_EXTENSION_ACTIVITY,
        title: 'Other Extension Activity Master',
        category: 'All Masters',
        subcategory: 'Training & Extension Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.TRAINING_EXTENSION_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.TRAINING_EXTENSION_MASTERS,
        fields: FIELD_GROUPS.TRAINING_CLIENTELE_MASTER,
        moduleCode: 'all_masters_other_extension_activity_master',
    },
    {
        path: ENTITY_PATHS.EVENTS,
        title: 'Events Master',
        category: 'All Masters',
        subcategory: 'Training & Extension Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.TRAINING_EXTENSION_MASTERS,
        siblings: [],
        fields: FIELD_GROUPS.EVENTS_MASTER,
        moduleCode: 'all_masters_events_master',
    },

    // Production - Product Masters
    {
        path: ENTITY_PATHS.PRODUCT_CATEGORY,
        title: 'Product Category Master',
        category: 'All Masters',
        subcategory: 'Production & Projects Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.PRODUCTION_PROJECTS_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.PRODUCT_MASTERS,
        fields: FIELD_GROUPS.PRODUCT_CATEGORY_MASTER,
        moduleCode: 'all_masters_products_master',
    },
    {
        path: ENTITY_PATHS.PRODUCT_TYPE,
        title: 'Product Type Master',
        category: 'All Masters',
        subcategory: 'Production & Projects Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.PRODUCTION_PROJECTS_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.PRODUCT_MASTERS,
        fields: FIELD_GROUPS.PRODUCT_TYPE_MASTER,
        moduleCode: 'all_masters_products_master',
    },
    {
        path: ENTITY_PATHS.PRODUCT,
        title: 'Products Master',
        category: 'All Masters',
        subcategory: 'Production & Projects Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.PRODUCTION_PROJECTS_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.PRODUCT_MASTERS,
        fields: FIELD_GROUPS.PRODUCT_MASTER,
        moduleCode: 'all_masters_products_master',
    },

    // CRA Masters
    {
        path: ENTITY_PATHS.CRA_CROPPING_SYSTEM,
        title: 'Cropping System Master',
        category: 'All Masters',
        subcategory: 'Production & Projects Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.PRODUCTION_PROJECTS_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.CRA_MASTERS,
        fields: FIELD_GROUPS.CRA_CROPPING_SYSTEM_MASTER,
        moduleCode: 'all_masters_climate_master',
    },
    {
        path: ENTITY_PATHS.CRA_FARMING_SYSTEM,
        title: 'Farming System Master',
        category: 'All Masters',
        subcategory: 'Production & Projects Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.PRODUCTION_PROJECTS_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.CRA_MASTERS,
        fields: FIELD_GROUPS.CRA_FARMING_SYSTEM_MASTER,
        moduleCode: 'all_masters_climate_master',
    },

    // ARYA Masters
    {
        path: ENTITY_PATHS.ARYA_ENTERPRISE,
        title: 'ARYA Enterprise Master',
        category: 'All Masters',
        subcategory: 'Production & Projects Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.PRODUCTION_PROJECTS_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.ARYA_MASTERS,
        fields: FIELD_GROUPS.ARYA_ENTERPRISE_MASTER,
        moduleCode: 'all_masters_arya_master',
    },
    {
        path: ENTITY_PATHS.TSP_SCSP_TYPE,
        title: 'TSP/SCSP Type Master',
        category: 'All Masters',
        subcategory: 'Production & Projects Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.PRODUCTION_PROJECTS_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.TSP_SCSP_MASTERS,
        fields: FIELD_GROUPS.CROP_TYPE_MASTER,
        moduleCode: 'all_masters_tsp_scsp_master',
    },
    {
        path: ENTITY_PATHS.TSP_SCSP_ACTIVITY,
        title: 'TSP/SCSP Activity Master',
        category: 'All Masters',
        subcategory: 'Production & Projects Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.PRODUCTION_PROJECTS_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.TSP_SCSP_MASTERS,
        fields: FIELD_GROUPS.FLD_ACTIVITY_MASTER,
        moduleCode: 'all_masters_tsp_scsp_master',
    },
    {
        path: ENTITY_PATHS.NATURAL_FARMING_ACTIVITY,
        title: 'Natural Farming Activity Master',
        category: 'All Masters',
        subcategory: 'Production & Projects Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.PRODUCTION_PROJECTS_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.NATURAL_FARMING_MASTERS,
        fields: [FIELD_NAMES.ACTIVITY_NAME] as const,
        moduleCode: 'all_masters_natural_farming_master',
    },
    {
        path: ENTITY_PATHS.NATURAL_FARMING_SOIL_PARAMETER,
        title: 'Natural Farming Soil Parameter Master',
        category: 'All Masters',
        subcategory: 'Production & Projects Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.PRODUCTION_PROJECTS_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.NATURAL_FARMING_MASTERS,
        fields: [FIELD_NAMES.TYPE] as const,
        moduleCode: 'all_masters_natural_farming_master',
    },

    // Agri Drone Masters
    {
        path: ENTITY_PATHS.AGRI_DRONE_DEMONSTRATIONS_ON,
        title: 'Agri-Drone Demonstrations On Master',
        category: 'All Masters',
        subcategory: 'Production & Projects Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.PRODUCTION_PROJECTS_MASTERS,
        siblings: [],
        fields: [FIELD_NAMES.DEMONSTRATIONS_ON] as const,
        moduleCode: 'all_masters_agri_drone_master',
    },

    // Publications
    {
        path: ENTITY_PATHS.PUBLICATION_ITEM,
        title: 'Publication Items Master',
        category: 'All Masters',
        subcategory: 'Publications Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.PUBLICATIONS_MASTERS,
        siblings: [ENTITY_PATHS.PUBLICATION_ITEM],
        fields: FIELD_GROUPS.PUBLICATION_ITEM_MASTER,
        moduleCode: 'all_masters_publication_master',
    },

    // Other Masters
    {
        path: ENTITY_PATHS.STAFF_CATEGORY,
        title: 'Staff Category Master',
        category: 'All Masters',
        subcategory: 'Other Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.OTHER_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.EMPLOYEE_MASTERS,
        fields: FIELD_GROUPS.STAFF_CATEGORY_MASTER,
        moduleCode: 'all_masters_staff_category_master',
    },
    {
        path: ENTITY_PATHS.PAY_LEVEL,
        title: 'Pay Level Master',
        category: 'All Masters',
        subcategory: 'Other Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.OTHER_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.EMPLOYEE_MASTERS,
        fields: FIELD_GROUPS.PAY_LEVEL_MASTER,
        moduleCode: 'all_masters_pay_level_master',
    },
    {
        path: ENTITY_PATHS.DISCIPLINE,
        title: 'Discipline Master',
        category: 'All Masters',
        subcategory: 'Other Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.OTHER_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.EMPLOYEE_MASTERS,
        fields: FIELD_GROUPS.DISCIPLINE_MASTER,
        moduleCode: 'all_masters_discipline_master',
    },
    {
        path: ENTITY_PATHS.SANCTIONED_POST,
        title: 'Sanctioned Post Master',
        category: 'All Masters',
        subcategory: 'Other Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.OTHER_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.EMPLOYEE_MASTERS,
        fields: FIELD_GROUPS.SANCTIONED_POST_MASTER,
        moduleCode: 'all_masters_sanctioned_post_master',
    },
    {
        path: ENTITY_PATHS.SEASON,
        title: 'Season Master',
        category: 'All Masters',
        subcategory: 'Other Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.OTHER_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.CALENDAR_MASTERS,
        fields: FIELD_GROUPS.SEASON_MASTER,
        moduleCode: 'all_masters_season_master',
    },
    {
        path: ENTITY_PATHS.YEAR,
        title: 'Year Master',
        category: 'All Masters',
        subcategory: 'Other Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.OTHER_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.CALENDAR_MASTERS,
        fields: FIELD_GROUPS.YEAR_MASTER,
        moduleCode: 'all_masters_year_master',
    },
    {
        path: ENTITY_PATHS.CROP_TYPE,
        title: 'Crop Type Master',
        category: 'All Masters',
        subcategory: 'Other Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.OTHER_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.CALENDAR_MASTERS,
        fields: FIELD_GROUPS.CROP_TYPE_MASTER,
        moduleCode: 'all_masters_crop_type_master',
    },
    {
        path: ENTITY_PATHS.INFRASTRUCTURE_MASTER,
        title: 'Infrastructure',
        category: 'All Masters',
        subcategory: 'Other Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.OTHER_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.RESOURCE_MASTERS,
        fields: FIELD_GROUPS.TRAINING_CLIENTELE_MASTER,
        moduleCode: 'all_masters_infrastructure_master',
    },
    {
        path: ENTITY_PATHS.IMPORTANT_DAY,
        title: 'Important Day Master',
        category: 'All Masters',
        subcategory: 'Other Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.OTHER_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.CALENDAR_MASTERS,
        fields: FIELD_GROUPS.IMPORTANT_DAY_MASTER,
        moduleCode: 'all_masters_events_master',
    },
    {
        path: ENTITY_PATHS.SOIL_WATER_ANALYSIS,
        title: 'Soil Water',
        category: 'All Masters',
        subcategory: 'Other Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.OTHER_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.RESOURCE_MASTERS,
        fields: FIELD_GROUPS.SOIL_WATER_ANALYSIS_MASTER,
        moduleCode: 'all_masters_soil_water_analysis_master',
    },
    {
        path: ENTITY_PATHS.NARI_ACTIVITY,
        title: 'NARI Activity Master',
        category: 'All Masters',
        subcategory: 'Other Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.OTHER_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.NARI_MASTERS,
        fields: FIELD_GROUPS.FLD_ACTIVITY_MASTER,
        moduleCode: 'all_masters_nari_activity_master',
    },
    {
        path: ENTITY_PATHS.NARI_CROP_CATEGORY,
        title: 'NARI Crop Category Master',
        category: 'All Masters',
        subcategory: 'Other Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.OTHER_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.NARI_MASTERS,
        fields: [FIELD_NAMES.NAME] as const,
        moduleCode: 'all_masters_nari_activity_master',
    },
    {
        path: ENTITY_PATHS.NARI_NUTRITION_GARDEN_TYPE,
        title: 'NARI Nutrition Garden Type Master',
        category: 'All Masters',
        subcategory: 'Other Masters',
        parent: '/all-master',
        subcategoryPath: ENTITY_PATHS.OTHER_MASTERS,
        siblings: MASTER_SIBLING_GROUPS.NARI_MASTERS,
        fields: FIELD_GROUPS.TRAINING_CLIENTELE_MASTER,
        moduleCode: 'all_masters_nari_garden_type_master',
    },
    {
        path: ENTITY_PATHS.NICRA_CATEGORY,
        title: 'NICRA Category Master',
        category: 'All Masters',
        subcategory: 'Other Masters',
        parent: '/all-master',
        subcategoryPath: '/all-master/other-masters',
        siblings: MASTER_SIBLING_GROUPS.NICRA_MASTERS,
        fields: FIELD_GROUPS.NICRA_CATEGORY_MASTER,
        moduleCode: 'all_masters_nicra_master',
    },
    {
        path: ENTITY_PATHS.NICRA_SUB_CATEGORY,
        title: 'NICRA Sub-category Master',
        category: 'All Masters',
        subcategory: 'Other Masters',
        parent: '/all-master',
        subcategoryPath: '/all-master/other-masters',
        siblings: MASTER_SIBLING_GROUPS.NICRA_MASTERS,
        fields: FIELD_GROUPS.NICRA_SUB_CATEGORY_MASTER,
        moduleCode: 'all_masters_nicra_master',
    },
    {
        path: ENTITY_PATHS.NICRA_SEED_BANK_FODDER_BANK,
        title: 'NICRA Seed/Fodder Bank Master',
        category: 'All Masters',
        subcategory: 'Other Masters',
        parent: '/all-master',
        subcategoryPath: '/all-master/other-masters',
        siblings: MASTER_SIBLING_GROUPS.NICRA_MASTERS,
        fields: FIELD_GROUPS.NICRA_SEED_BANK_FODDER_BANK_MASTER,
        moduleCode: 'all_masters_nicra_master',
    },
    {
        path: ENTITY_PATHS.NICRA_DIGNITARY_TYPE,
        title: 'NICRA Dignitary Type Master',
        category: 'All Masters',
        subcategory: 'Other Masters',
        parent: '/all-master',
        subcategoryPath: '/all-master/other-masters',
        siblings: MASTER_SIBLING_GROUPS.NICRA_MASTERS,
        fields: [FIELD_NAMES.TYPE] as const,
        moduleCode: 'all_masters_nicra_master',
    },
    {
        path: ENTITY_PATHS.NICRA_PI_TYPE,
        title: 'NICRA PI/CO-PI Type Master',
        category: 'All Masters',
        subcategory: 'Other Masters',
        parent: '/all-master',
        subcategoryPath: '/all-master/other-masters',
        siblings: MASTER_SIBLING_GROUPS.NICRA_MASTERS,
        fields: [FIELD_NAMES.TYPE] as const,
        moduleCode: 'all_masters_nicra_master',
    },
    {
        path: ENTITY_PATHS.IMPACT_SPECIFIC_AREA,
        title: 'Impact Areas',
        category: 'All Masters',
        subcategory: 'Other Masters',
        parent: '/all-master',
        subcategoryPath: '/all-master/other-masters',
        siblings: MASTER_SIBLING_GROUPS.ANALYSIS_MASTERS,
        fields: FIELD_GROUPS.IMPACT_SPECIFIC_AREA_MASTER,
        moduleCode: 'all_masters_impact_area_master',
    },
    {
        path: ENTITY_PATHS.ENTERPRISE_TYPE,
        title: 'Enterprises',
        category: 'All Masters',
        subcategory: 'Other Masters',
        parent: '/all-master',
        subcategoryPath: '/all-master/other-masters',
        siblings: MASTER_SIBLING_GROUPS.ANALYSIS_MASTERS,
        fields: FIELD_GROUPS.ENTERPRISE_TYPE_MASTER,
        moduleCode: 'all_masters_enterprise_type_master',
    },
    {
        path: ENTITY_PATHS.ACCOUNT_TYPE,
        title: 'Account Types',
        category: 'All Masters',
        subcategory: 'Other Masters',
        parent: '/all-master',
        subcategoryPath: '/all-master/other-masters',
        siblings: MASTER_SIBLING_GROUPS.ANALYSIS_MASTERS,
        fields: FIELD_GROUPS.ACCOUNT_TYPE_MASTER,
        moduleCode: 'all_masters_account_type_master',
    },
    {
        path: ENTITY_PATHS.PROGRAMME_TYPE,
        title: 'Programs',
        category: 'All Masters',
        subcategory: 'Other Masters',
        parent: '/all-master',
        subcategoryPath: '/all-master/other-masters',
        siblings: MASTER_SIBLING_GROUPS.ANALYSIS_MASTERS,
        fields: FIELD_GROUPS.PROGRAMME_TYPE_MASTER,
        moduleCode: 'all_masters_programme_type_master',
    },
    {
        path: ENTITY_PATHS.PPV_FRA_TRAINING_TYPE,
        title: 'PPV & FRA',
        category: 'All Masters',
        subcategory: 'Other Masters',
        parent: '/all-master',
        subcategoryPath: '/all-master/other-masters',
        siblings: MASTER_SIBLING_GROUPS.ANALYSIS_MASTERS,
        fields: FIELD_GROUPS.PPV_FRA_TRAINING_TYPE_MASTER,
        moduleCode: 'all_masters_ppv_fra_training_type_master',
    },
    {
        path: ENTITY_PATHS.DIGNITARY_TYPE,
        title: 'VIP Dignitaries',
        category: 'All Masters',
        subcategory: 'Other Masters',
        parent: '/all-master',
        subcategoryPath: '/all-master/other-masters',
        siblings: MASTER_SIBLING_GROUPS.ANALYSIS_MASTERS,
        fields: [FIELD_NAMES.NAME] as const,
        moduleCode: 'all_masters_dignitary_type_master',
    },
    {
        path: ENTITY_PATHS.FINANCIAL_PROJECT,
        title: 'Financial Project Master',
        category: 'All Masters',
        subcategory: 'Other Masters',
        parent: '/all-master',
        subcategoryPath: '/all-master/other-masters',
        siblings: MASTER_SIBLING_GROUPS.PROJECT_BUDGET_MASTERS,
        fields: FIELD_GROUPS.FINANCIAL_PROJECT_MASTER,
        moduleCode: 'all_masters_financial_project_master',
    },
    {
        path: ENTITY_PATHS.FUNDING_AGENCY,
        title: 'Funding Agency Master',
        category: 'All Masters',
        subcategory: 'Other Masters',
        parent: '/all-master',
        subcategoryPath: '/all-master/other-masters',
        siblings: MASTER_SIBLING_GROUPS.PROJECT_BUDGET_MASTERS,
        fields: FIELD_GROUPS.FUNDING_AGENCY_MASTER,
        moduleCode: 'all_masters_funding_agency_master',
    },
]
