/**
 * Performance Indicator Routes Configuration
 *
 * Contains all route configurations for the "Performance Indicators" section.
 * Includes routes for Impact, District & Village Performance, Infrastructure Performance,
 * Financial Performance, and Linkages.
 */

import { ROUTE_PATHS } from '../../constants/routePaths'
import { FIELD_GROUPS } from '../../constants/fieldNames'
import { ROUTE_SIBLING_GROUPS } from '../routeSiblingGroups'
import { RouteConfig } from './types'

export const performanceIndicatorRoutes: RouteConfig[] = [
    // Impact
    {
        path: ROUTE_PATHS.PERFORMANCE.IMPACT.KVK_ACTIVITIES,
        title: 'Impact of KVK activities',
        description: 'Impact of KVK activities',
        category: 'Form Management',
        subcategory: 'Performance Indicators',
        parent: ROUTE_PATHS.PERFORMANCE.BASE,
        moduleCode: 'performance_indicators_impact',
        fields: FIELD_GROUPS.PERFORMANCE_IMPACT_KVK_ACTIVITIES,
        siblings: ROUTE_SIBLING_GROUPS.PERFORMANCE_IMPACT,
    },
    {
        path: ROUTE_PATHS.PERFORMANCE.IMPACT.ENTREPRENEURSHIP,
        title: 'Entrepreneurship',
        description: 'Entrepreneurship impact',
        category: 'Form Management',
        subcategory: 'Performance Indicators',
        parent: ROUTE_PATHS.PERFORMANCE.BASE,
        moduleCode: 'performance_indicators_impact',
        fields: FIELD_GROUPS.PERFORMANCE_IMPACT_ENTREPRENEURSHIP,
        siblings: ROUTE_SIBLING_GROUPS.PERFORMANCE_IMPACT,
    },
    {
        path: ROUTE_PATHS.PERFORMANCE.IMPACT.SUCCESS_STORIES,
        title: 'Success Stories',
        description: 'Success stories impact',
        category: 'Form Management',
        subcategory: 'Performance Indicators',
        parent: ROUTE_PATHS.PERFORMANCE.BASE,
        moduleCode: 'performance_indicators_impact',
        fields: FIELD_GROUPS.PERFORMANCE_IMPACT_SUCCESS_STORIES,
        siblings: ROUTE_SIBLING_GROUPS.PERFORMANCE_IMPACT,
    },

    // District and Village Performance
    {
        path: ROUTE_PATHS.PERFORMANCE.DISTRICT_VILLAGE.DISTRICT_LEVEL,
        title: 'District Level Data',
        description: 'District level performance data',
        category: 'Form Management',
        subcategory: 'Performance Indicators',
        parent: ROUTE_PATHS.PERFORMANCE.BASE,
        moduleCode: 'performance_indicators_district_village',
        fields: FIELD_GROUPS.PERFORMANCE_DISTRICT_LEVEL,
        siblings: ROUTE_SIBLING_GROUPS.PERFORMANCE_DISTRICT_VILLAGE,
    },
    {
        path: ROUTE_PATHS.PERFORMANCE.DISTRICT_VILLAGE.OPERATIONAL_AREA,
        title: 'Operational Area Details',
        description: 'Operational area details',
        category: 'Form Management',
        subcategory: 'Performance Indicators',
        parent: ROUTE_PATHS.PERFORMANCE.BASE,
        moduleCode: 'performance_indicators_district_village',
        fields: FIELD_GROUPS.PERFORMANCE_OPERATIONAL_AREA,
        siblings: ROUTE_SIBLING_GROUPS.PERFORMANCE_DISTRICT_VILLAGE,
    },
    {
        path: ROUTE_PATHS.PERFORMANCE.DISTRICT_VILLAGE.VILLAGE_ADOPTION,
        title: 'Village Adoption Programme',
        description: 'Village adoption programme details',
        category: 'Form Management',
        subcategory: 'Performance Indicators',
        parent: ROUTE_PATHS.PERFORMANCE.BASE,
        moduleCode: 'performance_indicators_district_village',
        fields: FIELD_GROUPS.PERFORMANCE_VILLAGE_ADOPTION,
        siblings: ROUTE_SIBLING_GROUPS.PERFORMANCE_DISTRICT_VILLAGE,
    },
    {
        path: ROUTE_PATHS.PERFORMANCE.DISTRICT_VILLAGE.PRIORITY_THRUST,
        title: 'Priority Thrust Area',
        description: 'Priority thrust area details',
        category: 'Form Management',
        subcategory: 'Performance Indicators',
        parent: ROUTE_PATHS.PERFORMANCE.BASE,
        moduleCode: 'performance_indicators_district_village',
        fields: FIELD_GROUPS.PERFORMANCE_PRIORITY_THRUST,
        siblings: ROUTE_SIBLING_GROUPS.PERFORMANCE_DISTRICT_VILLAGE,
    },

    // Infrastructure Performance
    {
        path: ROUTE_PATHS.PERFORMANCE.INFRASTRUCTURE.DEMONSTRATION_UNITS,
        title: 'Demonstration Units',
        description: 'Demonstration units details',
        category: 'Form Management',
        subcategory: 'Performance Indicators',
        parent: ROUTE_PATHS.PERFORMANCE.BASE,
        moduleCode: 'performance_indicators_infrastructure',
        fields: FIELD_GROUPS.PERFORMANCE_DEMONSTRATION_UNITS,
        siblings: ROUTE_SIBLING_GROUPS.PERFORMANCE_INFRASTRUCTURE,
    },
    {
        path: ROUTE_PATHS.PERFORMANCE.INFRASTRUCTURE.INSTRUCTIONAL_FARM_CROPS,
        title: 'Instructional Farm (crops)',
        description: 'Instructional farm crops details',
        category: 'Form Management',
        subcategory: 'Performance Indicators',
        parent: ROUTE_PATHS.PERFORMANCE.BASE,
        moduleCode: 'performance_indicators_infrastructure',
        fields: FIELD_GROUPS.PERFORMANCE_INSTRUCTIONAL_FARM_CROPS,
        siblings: ROUTE_SIBLING_GROUPS.PERFORMANCE_INFRASTRUCTURE,
    },
    {
        path: ROUTE_PATHS.PERFORMANCE.INFRASTRUCTURE.PRODUCTION_UNITS,
        title: 'Production Units',
        description: 'Production units details',
        category: 'Form Management',
        subcategory: 'Performance Indicators',
        parent: ROUTE_PATHS.PERFORMANCE.BASE,
        moduleCode: 'performance_indicators_infrastructure',
        fields: FIELD_GROUPS.PERFORMANCE_PRODUCTION_UNITS,
        siblings: ROUTE_SIBLING_GROUPS.PERFORMANCE_INFRASTRUCTURE,
    },
    {
        path: ROUTE_PATHS.PERFORMANCE.INFRASTRUCTURE.INSTRUCTIONAL_FARM_LIVESTOCK,
        title: 'Instructional Farm (livestock)',
        description: 'Instructional farm livestock details',
        category: 'Form Management',
        subcategory: 'Performance Indicators',
        parent: ROUTE_PATHS.PERFORMANCE.BASE,
        moduleCode: 'performance_indicators_infrastructure',
        fields: FIELD_GROUPS.PERFORMANCE_INSTRUCTIONAL_FARM_LIVESTOCK,
        siblings: ROUTE_SIBLING_GROUPS.PERFORMANCE_INFRASTRUCTURE,
    },
    {
        path: ROUTE_PATHS.PERFORMANCE.INFRASTRUCTURE.HOSTEL,
        title: 'Hostel Facilities',
        description: 'Hostel facilities details',
        category: 'Form Management',
        subcategory: 'Performance Indicators',
        parent: ROUTE_PATHS.PERFORMANCE.BASE,
        moduleCode: 'performance_indicators_infrastructure',
        fields: FIELD_GROUPS.PERFORMANCE_HOSTEL,
        siblings: ROUTE_SIBLING_GROUPS.PERFORMANCE_INFRASTRUCTURE,
    },
    {
        path: ROUTE_PATHS.PERFORMANCE.INFRASTRUCTURE.STAFF_QUARTERS,
        title: 'Staff Quarters',
        description: 'Staff quarters details',
        category: 'Form Management',
        subcategory: 'Performance Indicators',
        parent: ROUTE_PATHS.PERFORMANCE.BASE,
        moduleCode: 'performance_indicators_infrastructure',
        fields: FIELD_GROUPS.PERFORMANCE_STAFF_QUARTERS,
        siblings: ROUTE_SIBLING_GROUPS.PERFORMANCE_INFRASTRUCTURE,
    },
    {
        path: ROUTE_PATHS.PERFORMANCE.INFRASTRUCTURE.RAINWATER_HARVESTING,
        title: 'Rain Water Harvesting',
        description: 'Rain water harvesting details',
        category: 'Form Management',
        subcategory: 'Performance Indicators',
        parent: ROUTE_PATHS.PERFORMANCE.BASE,
        moduleCode: 'performance_indicators_infrastructure',
        fields: FIELD_GROUPS.PERFORMANCE_RAINWATER_HARVESTING,
        siblings: ROUTE_SIBLING_GROUPS.PERFORMANCE_INFRASTRUCTURE,
    },

    // Financial Performance
    {
        path: ROUTE_PATHS.PERFORMANCE.FINANCIAL.BUDGET_DETAILS,
        title: 'Budget Details',
        description: 'Budget details',
        category: 'Form Management',
        subcategory: 'Performance Indicators',
        parent: ROUTE_PATHS.PERFORMANCE.BASE,
        moduleCode: 'performance_indicators_financial',
        fields: FIELD_GROUPS.PERFORMANCE_BUDGET_DETAILS,
        siblings: ROUTE_SIBLING_GROUPS.PERFORMANCE_FINANCIAL,
    },
    {
        path: ROUTE_PATHS.PERFORMANCE.FINANCIAL.PROJECT_BUDGET,
        title: 'Project-wise Budget',
        description: 'Project-wise budget details',
        category: 'Form Management',
        subcategory: 'Performance Indicators',
        parent: ROUTE_PATHS.PERFORMANCE.BASE,
        moduleCode: 'performance_indicators_financial',
        fields: FIELD_GROUPS.PERFORMANCE_PROJECT_BUDGET,
        siblings: ROUTE_SIBLING_GROUPS.PERFORMANCE_FINANCIAL,
    },
    {
        path: ROUTE_PATHS.PERFORMANCE.FINANCIAL.REVOLVING_FUND,
        title: 'Revolving Fund Status',
        description: 'Revolving fund status',
        category: 'Form Management',
        subcategory: 'Performance Indicators',
        parent: ROUTE_PATHS.PERFORMANCE.BASE,
        moduleCode: 'performance_indicators_financial',
        fields: FIELD_GROUPS.PERFORMANCE_REVOLVING_FUND,
        siblings: ROUTE_SIBLING_GROUPS.PERFORMANCE_FINANCIAL,
    },
    {
        path: ROUTE_PATHS.PERFORMANCE.FINANCIAL.REVENUE_GENERATION,
        title: 'Revenue generation',
        description: 'Revenue generation details',
        category: 'Form Management',
        subcategory: 'Performance Indicators',
        parent: ROUTE_PATHS.PERFORMANCE.BASE,
        moduleCode: 'performance_indicators_financial',
        fields: FIELD_GROUPS.PERFORMANCE_REVENUE_GENERATION,
        siblings: ROUTE_SIBLING_GROUPS.PERFORMANCE_FINANCIAL,
    },
    {
        path: ROUTE_PATHS.PERFORMANCE.FINANCIAL.RESOURCE_GENERATION,
        title: 'Resource Generation',
        description: 'Resource generation details',
        category: 'Form Management',
        subcategory: 'Performance Indicators',
        parent: ROUTE_PATHS.PERFORMANCE.BASE,
        moduleCode: 'performance_indicators_financial',
        fields: FIELD_GROUPS.PERFORMANCE_RESOURCE_GENERATION,
        siblings: ROUTE_SIBLING_GROUPS.PERFORMANCE_FINANCIAL,
    },

    // Linkages
    {
        path: ROUTE_PATHS.PERFORMANCE.LINKAGES.FUNCTIONAL_LINKAGE,
        title: 'Functional Linkage',
        description: 'Functional linkage details',
        category: 'Form Management',
        subcategory: 'Performance Indicators',
        parent: ROUTE_PATHS.PERFORMANCE.BASE,
        moduleCode: 'performance_indicators_linkages',
        fields: FIELD_GROUPS.PERFORMANCE_FUNCTIONAL_LINKAGE,
        siblings: ROUTE_SIBLING_GROUPS.PERFORMANCE_LINKAGES,
    },
    {
        path: ROUTE_PATHS.PERFORMANCE.LINKAGES.SPECIAL_PROGRAMMES,
        title: 'Special Programmes',
        description: 'Special programmes details',
        category: 'Form Management',
        subcategory: 'Performance Indicators',
        parent: ROUTE_PATHS.PERFORMANCE.BASE,
        moduleCode: 'performance_indicators_linkages',
        fields: FIELD_GROUPS.PERFORMANCE_SPECIAL_PROGRAMMES,
        siblings: ROUTE_SIBLING_GROUPS.PERFORMANCE_LINKAGES,
    },
]
