/**
 * Projects Routes Configuration
 *
 * Contains all route configurations for the "Projects" section under Achievements.
 * Includes routes for CFLD, CRA, FPO, DRMR, NARI, ARYA, CSISA, TSP/SCSP, NICRA,
 * Natural Farming, Agri-Drone, Seed Hub, and Other Programs.
 */

import { ROUTE_PATHS } from '../../constants/routePaths'
import { FIELD_GROUPS } from '../../constants/fieldNames'
import { ROUTE_SIBLING_GROUPS } from '../routeSiblingGroups'
import { RouteConfig } from './types'

export const projectsRoutes: RouteConfig[] = [
    // CFLD
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.CFLD.TECHNICAL_PARAMETER,
        title: 'Technical Parameter',
        description: 'CFLD Technical Parameters',
        category: 'Projects',
        subcategory: 'CFLD',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.BASE,
        moduleCode: 'achievements_projects',
        fields: FIELD_GROUPS.CFLD_TECHNICAL_PARAMETER,
        siblings: ROUTE_SIBLING_GROUPS.CFLD,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.CFLD.EXTENSION_ACTIVITY,
        title: 'Extension Activity',
        description: 'CFLD Extension Activities',
        category: 'Projects',
        subcategory: 'CFLD',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.BASE,
        moduleCode: 'achievements_projects',
        fields: FIELD_GROUPS.CFLD_EXTENSION_ACTIVITY,
        siblings: ROUTE_SIBLING_GROUPS.CFLD,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.CFLD.BUDGET_UTILIZATION,
        title: 'Budget Utilization',
        description: 'CFLD Budget Utilization',
        category: 'Projects',
        subcategory: 'CFLD',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.BASE,
        moduleCode: 'achievements_projects',
        fields: FIELD_GROUPS.CFLD_BUDGET_UTILIZATION,
        siblings: ROUTE_SIBLING_GROUPS.CFLD,
    },

    // CRA
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.CRA.DETAILS,
        title: 'Climate Resilient',
        description: 'Climate Resilient Agriculture Details',
        category: 'Projects',
        subcategory: 'CRA',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.BASE,
        moduleCode: 'achievements_projects',
        fields: FIELD_GROUPS.CRA_DETAILS,
        siblings: ROUTE_SIBLING_GROUPS.CRA,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.CRA.EXTENSION_ACTIVITY,
        title: 'Extension Activity',
        description: 'CRA Extension Activities',
        category: 'Projects',
        subcategory: 'CRA',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.BASE,
        moduleCode: 'achievements_projects',
        fields: FIELD_GROUPS.CRA_EXTENSION_ACTIVITY,
        siblings: ROUTE_SIBLING_GROUPS.CRA,
    },

    // FPO
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.FPO.DETAILS,
        title: 'FPO Details',
        description: 'Formation and Promotion of FPOs as CBBOs under NCDC funding',
        category: 'Projects',
        subcategory: 'FPO',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.BASE,
        moduleCode: 'achievements_projects',
        fields: FIELD_GROUPS.FPO_DETAILS,
        siblings: ROUTE_SIBLING_GROUPS.FPO,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.FPO.MANAGEMENT,
        title: 'FPO Management',
        description: 'FPO Management',
        category: 'Projects',
        subcategory: 'FPO',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.BASE,
        moduleCode: 'achievements_projects',
        fields: FIELD_GROUPS.FPO_MANAGEMENT,
        siblings: ROUTE_SIBLING_GROUPS.FPO,
    },

    // DRMR
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.DRMR.DETAILS,
        title: 'DRMR Details',
        description: 'DRMR Program Details',
        category: 'Projects',
        subcategory: 'DRMR',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.BASE,
        moduleCode: 'achievements_projects',
        fields: FIELD_GROUPS.DRMR_DETAILS,
        siblings: ROUTE_SIBLING_GROUPS.DRMR,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.DRMR.ACTIVITY,
        title: 'DRMR Activity',
        description: 'DRMR Activities',
        category: 'Projects',
        subcategory: 'DRMR',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.BASE,
        moduleCode: 'achievements_projects',
        fields: FIELD_GROUPS.DRMR_ACTIVITY,
        siblings: ROUTE_SIBLING_GROUPS.DRMR,
    },

    // NARI
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NARI.NUTRI_SMART,
        title: 'Nutrition Garden',
        description: 'Details of Nutrition Garden in Nutri-Smart village',
        category: 'Projects',
        subcategory: 'NARI',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.BASE,
        moduleCode: 'achievements_projects',
        fields: FIELD_GROUPS.NARI_NUTRI_SMART,
        siblings: ROUTE_SIBLING_GROUPS.NARI,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NARI.BIO_FORTIFIED,
        title: 'Bio-fortified Crops',
        description: 'Details of Bio-fortified crops used in Nutri-Smart village',
        category: 'Projects',
        subcategory: 'NARI',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.BASE,
        moduleCode: 'achievements_projects',
        fields: FIELD_GROUPS.NARI_BIO_FORTIFIED,
        siblings: ROUTE_SIBLING_GROUPS.NARI,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NARI.VALUE_ADDITION,
        title: 'Value Addition',
        description: 'Details of Value addition',
        category: 'Projects',
        subcategory: 'NARI',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.BASE,
        moduleCode: 'achievements_projects',
        fields: FIELD_GROUPS.NARI_VALUE_ADDITION,
        siblings: ROUTE_SIBLING_GROUPS.NARI,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NARI.TRAINING_PROGRAMM,
        title: 'Training Programmes',
        description: 'Training programmes in Nutri-Smart village',
        category: 'Projects',
        subcategory: 'NARI',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.BASE,
        moduleCode: 'achievements_projects',
        fields: FIELD_GROUPS.NARI_TRAINING_PROGRAMM,
        siblings: ROUTE_SIBLING_GROUPS.NARI,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NARI.EXTENSION_ACTIVITIES,
        title: 'Extension Activities',
        description: 'Extension activities under NARI',
        category: 'Projects',
        subcategory: 'NARI',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.BASE,
        moduleCode: 'achievements_projects',
        fields: FIELD_GROUPS.NARI_EXTENSION_ACTIVITIES,
        siblings: ROUTE_SIBLING_GROUPS.NARI,
    },

    // ARYA
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.ARYA.CURRENT,
        title: 'Current Year',
        description: 'ARYA Current Year Details',
        category: 'Projects',
        subcategory: 'ARYA',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.BASE,
        moduleCode: 'achievements_projects',
        fields: FIELD_GROUPS.ARYA_CURRENT,
        siblings: ROUTE_SIBLING_GROUPS.ARYA,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.ARYA.EVALUATION,
        title: 'Previous Year',
        description: 'ARYA Previous Year Evaluation',
        category: 'Projects',
        subcategory: 'ARYA',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.BASE,
        moduleCode: 'achievements_projects',
        fields: FIELD_GROUPS.ARYA_EVALUATION,
        siblings: ROUTE_SIBLING_GROUPS.ARYA,
    },

    // Direct links (no siblings)
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.CSISA,
        title: 'CSISA',
        description: 'Cereal Systems Initiative for South Asia (CSISA)',
        category: 'Projects',
        subcategory: 'CSISA',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.BASE,
        moduleCode: 'achievements_projects',
        fields: FIELD_GROUPS.CSISA,
    },
    // TSP/SCSP — split into two siblings under the same group. Both
    // submit to the same backend endpoint; useTspScspFilteredProjectData
    // hardcodes `type` per page and filters the rows client-side.
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.TSP_SCSP.TSP,
        title: 'TSP Activities',
        description: 'Tribal Sub Plan (TSP) Activities',
        category: 'Projects',
        subcategory: 'TSP/SCSP',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.BASE,
        moduleCode: 'achievements_projects',
        fields: FIELD_GROUPS.TSP_SCSP_ACTIVITIES,
        siblings: ROUTE_SIBLING_GROUPS.TSP_SCSP,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.TSP_SCSP.SCSP,
        title: 'SCSP Activities',
        description: 'Scheduled Caste Sub Plan (SCSP) Activities',
        category: 'Projects',
        subcategory: 'TSP/SCSP',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.BASE,
        moduleCode: 'achievements_projects',
        fields: FIELD_GROUPS.TSP_SCSP_ACTIVITIES,
        siblings: ROUTE_SIBLING_GROUPS.TSP_SCSP,
    },

    // NICRA
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.BASIC_INFORMATION,
        title: 'Basic Information',
        description: 'NICRA Basic Information',
        category: 'Projects',
        subcategory: 'NICRA',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.BASE,
        moduleCode: 'achievements_projects',
        fields: FIELD_GROUPS.NICRA_BASIC_INFORMATION,
        siblings: ROUTE_SIBLING_GROUPS.NICRA_BASE,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.DETAILS,
        title: 'Details',
        description: 'NICRA Details',
        category: 'Projects',
        subcategory: 'NICRA',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.BASE,
        moduleCode: 'achievements_projects',
        siblings: ROUTE_SIBLING_GROUPS.NICRA_BASE,
        fields: FIELD_GROUPS.NICRA_DETAILS,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.TRAINING,
        title: 'Training',
        description: 'NICRA Training',
        category: 'Projects',
        subcategory: 'NICRA',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.BASE,
        moduleCode: 'achievements_projects',
        siblings: ROUTE_SIBLING_GROUPS.NICRA_BASE,
        fields: FIELD_GROUPS.NICRA_TRAINING,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.EXTENSION_ACTIVITY,
        title: 'Extension Activity',
        description: 'NICRA Extension Activity',
        category: 'Projects',
        subcategory: 'NICRA',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.BASE,
        moduleCode: 'achievements_projects',
        fields: FIELD_GROUPS.NICRA_EXTENSION_ACTIVITY,
        siblings: ROUTE_SIBLING_GROUPS.NICRA_BASE,
    },

    // NICRA Others - using centralized paths
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.OTHERS.INTERVENTION,
        title: 'Intervention',
        description: 'NICRA Others - Intervention',
        category: 'Projects',
        subcategory: 'NICRA Others',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.BASE,
        moduleCode: 'achievements_projects',
        siblings: ROUTE_SIBLING_GROUPS.NICRA_OTHERS,
        fields: FIELD_GROUPS.NICRA_OTHERS_INTERVENTION,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.OTHERS.REVENUE_GENERATED,
        title: 'Revenue Generated',
        description: 'NICRA Others - Revenue Generated',
        category: 'Projects',
        subcategory: 'NICRA Others',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.BASE,
        moduleCode: 'achievements_projects',
        siblings: ROUTE_SIBLING_GROUPS.NICRA_OTHERS,
        fields: FIELD_GROUPS.NICRA_OTHERS_REVENUE_GENERATED,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.OTHERS.CUSTOM_HIRING,
        title: 'Custom Hiring',
        description: 'NICRA Others - Custom Hiring of Farm-Implement',
        category: 'Projects',
        subcategory: 'NICRA Others',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.BASE,
        moduleCode: 'achievements_projects',
        siblings: ROUTE_SIBLING_GROUPS.NICRA_OTHERS,
        fields: FIELD_GROUPS.NICRA_OTHERS_CUSTOM_HIRING,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.OTHERS.VCRMC,
        title: 'Village VCRMC',
        description: 'NICRA Others - Village wise VCRMC',
        category: 'Projects',
        subcategory: 'NICRA Others',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.BASE,
        moduleCode: 'achievements_projects',
        siblings: ROUTE_SIBLING_GROUPS.NICRA_OTHERS,
        fields: FIELD_GROUPS.NICRA_OTHERS_VCRMC,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.OTHERS.SOIL_HEALTH_CARD,
        title: 'Soil Health Card',
        description: 'NICRA Others - Soil Health Card',
        category: 'Projects',
        subcategory: 'NICRA Others',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.BASE,
        moduleCode: 'achievements_projects',
        siblings: ROUTE_SIBLING_GROUPS.NICRA_OTHERS,
        fields: FIELD_GROUPS.NICRA_OTHERS_SOIL_HEALTH_CARD,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.OTHERS.CONVERGENCE_PROGRAMME,
        title: 'Convergence',
        description: 'NICRA Others - Convergence Programme',
        category: 'Projects',
        subcategory: 'NICRA Others',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.BASE,
        moduleCode: 'achievements_projects',
        siblings: ROUTE_SIBLING_GROUPS.NICRA_OTHERS,
        fields: FIELD_GROUPS.NICRA_OTHERS_CONVERGENCE_PROGRAMME,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.OTHERS.DIGNITARIES_VISITED,
        title: 'Dignitaries',
        description: 'NICRA Others - Dignitaries Visited',
        category: 'Projects',
        subcategory: 'NICRA Others',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.BASE,
        moduleCode: 'achievements_projects',
        siblings: ROUTE_SIBLING_GROUPS.NICRA_OTHERS,
        fields: FIELD_GROUPS.NICRA_OTHERS_DIGNITARIES_VISITED,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.OTHERS.PI_COPI_LIST,
        title: 'PI & Co-PI',
        description: 'NICRA Others - PI & Co-PI List',
        category: 'Projects',
        subcategory: 'NICRA Others',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.BASE,
        moduleCode: 'achievements_projects',
        siblings: ROUTE_SIBLING_GROUPS.NICRA_OTHERS,
        fields: FIELD_GROUPS.NICRA_OTHERS_PI_COPI_LIST,
    },

    // Natural Farming
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NATURAL_FARMING.GEOGRAPHICAL_INFORMATION,
        title: 'Geographical',
        description: 'Geographical Information',
        category: 'Projects',
        subcategory: 'Natural Farming',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.BASE,
        moduleCode: 'achievements_projects',
        siblings: ROUTE_SIBLING_GROUPS.NATURAL_FARMING,
        fields: FIELD_GROUPS.NATURAL_FARMING_GEOGRAPHICAL_INFORMATION,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NATURAL_FARMING.PHYSICAL_INFORMATION,
        title: 'Physical',
        description: 'Physical Information',
        category: 'Projects',
        subcategory: 'Natural Farming',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.BASE,
        moduleCode: 'achievements_projects',
        siblings: ROUTE_SIBLING_GROUPS.NATURAL_FARMING,
        fields: FIELD_GROUPS.NATURAL_FARMING_PHYSICAL_INFORMATION,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NATURAL_FARMING.DEMONSTRATION_INFORMATION,
        title: 'Demonstration',
        description: 'Demonstration Information',
        category: 'Projects',
        subcategory: 'Natural Farming',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.BASE,
        moduleCode: 'achievements_projects',
        fields: FIELD_GROUPS.NATURAL_FARMING_DEMONSTRATION,
        siblings: ROUTE_SIBLING_GROUPS.NATURAL_FARMING,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NATURAL_FARMING.FARMERS_PRACTICING,
        title: 'Farmers Practicing',
        description: 'Farmers Already Practicing Natural Farming',
        category: 'Projects',
        subcategory: 'Natural Farming',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.BASE,
        moduleCode: 'achievements_projects',
        fields: FIELD_GROUPS.NATURAL_FARMING_FARMERS_PRACTICING,
        siblings: ROUTE_SIBLING_GROUPS.NATURAL_FARMING,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NATURAL_FARMING.BENEFICIARIES,
        title: 'Beneficiaries',
        description: 'Details of Beneficiaries',
        category: 'Projects',
        subcategory: 'Natural Farming',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.BASE,
        moduleCode: 'achievements_projects',
        fields: FIELD_GROUPS.NATURAL_FARMING_BENEFICIARIES,
        siblings: ROUTE_SIBLING_GROUPS.NATURAL_FARMING,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NATURAL_FARMING.SOIL_DATA,
        title: 'Soil Data',
        description: 'Soil Data Information',
        category: 'Projects',
        subcategory: 'Natural Farming',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.BASE,
        moduleCode: 'achievements_projects',
        siblings: ROUTE_SIBLING_GROUPS.NATURAL_FARMING,
        fields: FIELD_GROUPS.NATURAL_FARMING_SOIL_DATA,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NATURAL_FARMING.BUDGET_EXPENDITURE,
        title: 'Budget Expenditure',
        description: 'Budget Expenditure Information',
        category: 'Projects',
        subcategory: 'Natural Farming',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.BASE,
        moduleCode: 'achievements_projects',
        fields: FIELD_GROUPS.NATURAL_FARMING_BUDGET_EXPENDITURE,
        siblings: ROUTE_SIBLING_GROUPS.NATURAL_FARMING,
    },

    // Agri-Drone
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.AGRI_DRONE,
        title: 'Introduction',
        description: 'Agri-Drone Introduction',
        category: 'Projects',
        subcategory: 'Agri-Drone',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.BASE,
        moduleCode: 'achievements_projects',
        fields: FIELD_GROUPS.AGRI_DRONE_INTRODUCTION,
        siblings: ROUTE_SIBLING_GROUPS.AGRI_DRONE,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.DEMONSTRATION_DETAILS,
        title: 'Demonstration',
        description: 'Agri-Drone Demonstration Details',
        category: 'Projects',
        subcategory: 'Agri-Drone',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.BASE,
        moduleCode: 'achievements_projects',
        fields: FIELD_GROUPS.AGRI_DRONE_DEMONSTRATION,
        siblings: ROUTE_SIBLING_GROUPS.AGRI_DRONE,
    },

    // Other direct links
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.SEED_HUB_PROGRAM,
        title: 'Seed Hub Program',
        description: 'Seed Hub Program details',
        category: 'Projects',
        subcategory: 'Seed Hub',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.BASE,
        moduleCode: 'achievements_projects',
        fields: FIELD_GROUPS.SEED_HUB_PROGRAM,
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.OTHER_PROGRAM,
        title: 'Other Programmes',
        description: 'Other programmes organized by KVK',
        category: 'Projects',
        subcategory: 'Other',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.BASE,
        moduleCode: 'achievements_projects',
        fields: FIELD_GROUPS.OTHER_PROGRAM,
    },

    // DRMR
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.DRMR.DETAILS,
        title: 'DRMR Details',
        description: 'DRMR Implementation Details',
        category: 'Projects',
        subcategory: 'DRMR',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.BASE,
        moduleCode: 'achievements_projects',
        fields: FIELD_GROUPS.DRMR_DETAILS,
        siblings: [
            ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.DRMR.DETAILS,
            ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.DRMR.ACTIVITY,
        ],
    },
    {
        path: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.DRMR.ACTIVITY,
        title: 'DRMR Activity',
        description: 'DRMR Activity Details',
        category: 'Projects',
        subcategory: 'DRMR',
        parent: ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.BASE,
        moduleCode: 'achievements_projects',
        fields: FIELD_GROUPS.DRMR_ACTIVITY,
        siblings: [
            ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.DRMR.DETAILS,
            ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.DRMR.ACTIVITY,
        ],
    },
]
