/**
 * Master Sibling Groups
 *
 * Centralized sibling route groups for All Masters navigation.
 * These groups define which master routes should appear as tabs together.
 *
 * Usage:
 *   import { MASTER_SIBLING_GROUPS } from '@/config/masterSiblingGroups'
 *   siblings: MASTER_SIBLING_GROUPS.BASIC_MASTERS
 */

import { ENTITY_PATHS } from '../constants/entityConstants'

export const MASTER_SIBLING_GROUPS = {
    // Basic Masters
    BASIC_MASTERS: [
        ENTITY_PATHS.ZONES,
        ENTITY_PATHS.STATES,
        ENTITY_PATHS.DISTRICTS,
        ENTITY_PATHS.ORGANIZATIONS,
        ENTITY_PATHS.UNIVERSITIES,
        ENTITY_PATHS.KVK_MASTER,
    ],

    // OFT Masters
    OFT_MASTERS: [
        ENTITY_PATHS.OFT_SUBJECT,
        ENTITY_PATHS.OFT_THEMATIC_AREA,
    ],

    // FLD Masters
    FLD_MASTERS: [
        ENTITY_PATHS.FLD_SECTOR,
        ENTITY_PATHS.FLD_THEMATIC_AREA,
        ENTITY_PATHS.FLD_CATEGORY,
        ENTITY_PATHS.FLD_SUBCATEGORY,
        ENTITY_PATHS.FLD_CROP,
        ENTITY_PATHS.FLD_ACTIVITY,
    ],

    // CFLD Masters
    CFLD_MASTERS: [
        ENTITY_PATHS.CFLD_CROP,
    ],

    // Training Basic Masters
    TRAINING_BASIC_MASTERS: [
        ENTITY_PATHS.TRAINING_TYPE,
        ENTITY_PATHS.TRAINING_AREA,
        ENTITY_PATHS.TRAINING_THEMATIC,
        ENTITY_PATHS.TRAINING_CLIENTELE,
        ENTITY_PATHS.FUNDING_SOURCE,
    ],

    // Training Extension Masters
    TRAINING_EXTENSION_MASTERS: [
        ENTITY_PATHS.EXTENSION_ACTIVITY,
        ENTITY_PATHS.OTHER_EXTENSION_ACTIVITY,
    ],

    // Production & Projects Masters
    PRODUCT_MASTERS: [
        ENTITY_PATHS.PRODUCT_CATEGORY,
        ENTITY_PATHS.PRODUCT_TYPE,
        ENTITY_PATHS.PRODUCT,
    ],

    CRA_MASTERS: [
        ENTITY_PATHS.CRA_CROPPING_SYSTEM,
        ENTITY_PATHS.CRA_FARMING_SYSTEM,
    ],

    ARYA_MASTERS: [
        ENTITY_PATHS.ARYA_ENTERPRISE,
    ],

    TSP_SCSP_MASTERS: [
        ENTITY_PATHS.TSP_SCSP_TYPE,
        ENTITY_PATHS.TSP_SCSP_ACTIVITY,
    ],

    NATURAL_FARMING_MASTERS: [
        ENTITY_PATHS.NATURAL_FARMING_ACTIVITY,
        ENTITY_PATHS.NATURAL_FARMING_SOIL_PARAMETER,
    ],

    // Employee Masters
    EMPLOYEE_MASTERS: [
        ENTITY_PATHS.STAFF_CATEGORY,
        ENTITY_PATHS.PAY_LEVEL,
        ENTITY_PATHS.PAY_SCALE,
        ENTITY_PATHS.SANCTIONED_POST,
        ENTITY_PATHS.DISCIPLINE,
    ],

    // Calendar & Context Masters
    CALENDAR_MASTERS: [
        ENTITY_PATHS.SEASON,
        ENTITY_PATHS.CROP_TYPE,
        ENTITY_PATHS.IMPORTANT_DAY,
    ],

    // Analysis & Performance Masters
    RESOURCE_MASTERS: [
        ENTITY_PATHS.INFRASTRUCTURE_MASTER,
        ENTITY_PATHS.SOIL_WATER_ANALYSIS,
        ENTITY_PATHS.VEHICLE_PRESENT_STATUS,
        ENTITY_PATHS.EQUIPMENT_PRESENT_STATUS,
        ENTITY_PATHS.EQUIPMENT_TYPE,
        ENTITY_PATHS.EQUIPMENT_MASTER,
        ENTITY_PATHS.ASSET_FUNDING_SOURCE,
    ],

    ANALYSIS_MASTERS: [
        ENTITY_PATHS.IMPACT_SPECIFIC_AREA,
        ENTITY_PATHS.ENTERPRISE_TYPE,
        ENTITY_PATHS.ACCOUNT_TYPE,
        ENTITY_PATHS.PROGRAMME_TYPE,
        ENTITY_PATHS.PPV_FRA_TRAINING_TYPE,
        ENTITY_PATHS.DIGNITARY_TYPE,
    ],

    PROJECT_BUDGET_MASTERS: [
        ENTITY_PATHS.FUNDING_AGENCY,
        ENTITY_PATHS.FINANCIAL_PROJECT,
    ],

    NARI_MASTERS: [
        ENTITY_PATHS.NARI_ACTIVITY,
        ENTITY_PATHS.NARI_NUTRITION_GARDEN_TYPE,
        ENTITY_PATHS.NARI_CROP_CATEGORY,
    ],

    // NICRA Masters
    NICRA_MASTERS: [
        ENTITY_PATHS.NICRA_CATEGORY,
        ENTITY_PATHS.NICRA_SUB_CATEGORY,
        ENTITY_PATHS.NICRA_SEED_BANK_FODDER_BANK,
        ENTITY_PATHS.NICRA_DIGNITARY_TYPE,
        ENTITY_PATHS.NICRA_PI_TYPE,
    ],
} as const;
