/**
 * Route Sibling Groups
 *
 * Centralized sibling route groups for tab navigation.
 * These groups define which routes should appear as tabs together.
 *
 * Usage:
 *   import { ROUTE_SIBLING_GROUPS } from '@/config/routeSiblingGroups'
 *   siblings: ROUTE_SIBLING_GROUPS.FLD
 */

import { ROUTE_PATHS } from '../constants/routePaths'

export const ROUTE_SIBLING_GROUPS = {
    // FLD Siblings (includes OFT and all FLD sub-features)
    OFT_FLD: [
        ROUTE_PATHS.ACHIEVEMENTS.OFT,
        ROUTE_PATHS.ACHIEVEMENTS.FLD.BASE,
        ROUTE_PATHS.ACHIEVEMENTS.FLD.EXTENSION_TRAINING,
        ROUTE_PATHS.ACHIEVEMENTS.FLD.TECHNICAL_FEEDBACK,
    ] as const,

    // CFLD Siblings
    CFLD: [
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.CFLD.TECHNICAL_PARAMETER,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.CFLD.EXTENSION_ACTIVITY,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.CFLD.BUDGET_UTILIZATION,
    ],

    // CRA Siblings
    CRA: [
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.CRA.DETAILS,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.CRA.EXTENSION_ACTIVITY,
    ],

    // FPO Siblings
    FPO: [
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.FPO.DETAILS,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.FPO.MANAGEMENT,
    ],

    // DRMR Siblings
    DRMR: [
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.DRMR.DETAILS,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.DRMR.ACTIVITY,
    ],

    // NARI Siblings
    NARI: [
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NARI.NUTRI_SMART,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NARI.BIO_FORTIFIED,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NARI.VALUE_ADDITION,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NARI.TRAINING_PROGRAMM,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NARI.EXTENSION_ACTIVITIES,
    ],

    // ARYA Siblings
    ARYA: [
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.ARYA.CURRENT,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.ARYA.EVALUATION,
    ],

    // NICRA Base Siblings
    NICRA_BASE: [
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.BASIC_INFORMATION,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.DETAILS,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.TRAINING,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.EXTENSION_ACTIVITY,
    ],

    // NICRA Others Siblings
    NICRA_OTHERS: [
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.OTHERS.INTERVENTION,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.OTHERS.REVENUE_GENERATED,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.OTHERS.CUSTOM_HIRING,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.OTHERS.VCRMC,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.OTHERS.SOIL_HEALTH_CARD,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.OTHERS.CONVERGENCE_PROGRAMME,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.OTHERS.DIGNITARIES_VISITED,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.OTHERS.PI_COPI_LIST,
    ],

    // Natural Farming Siblings
    NATURAL_FARMING: [
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NATURAL_FARMING.GEOGRAPHICAL_INFORMATION,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NATURAL_FARMING.PHYSICAL_INFORMATION,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NATURAL_FARMING.DEMONSTRATION_INFORMATION,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NATURAL_FARMING.FARMERS_PRACTICING,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NATURAL_FARMING.BENEFICIARIES,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NATURAL_FARMING.SOIL_DATA,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NATURAL_FARMING.BUDGET_EXPENDITURE,
    ],

    // Agri-Drone Siblings
    AGRI_DRONE: [
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.AGRI_DRONE,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.DEMONSTRATION_DETAILS,
    ],

    // KVK View Siblings
    KVK_VIEW: [
        ROUTE_PATHS.ABOUT_KVK.VIEW_KVKS.DETAILS,
        ROUTE_PATHS.ABOUT_KVK.VIEW_KVKS.BANK,
        ROUTE_PATHS.ABOUT_KVK.VIEW_KVKS.EMPLOYEES,
        ROUTE_PATHS.ABOUT_KVK.VIEW_KVKS.VEHICLES,
        ROUTE_PATHS.ABOUT_KVK.VIEW_KVKS.EQUIPMENTS,
    ],

    // Soil Water Testing Siblings
    SOIL_WATER_TESTING: [
        ROUTE_PATHS.ACHIEVEMENTS.SOIL_EQUIPMENT,
        ROUTE_PATHS.ACHIEVEMENTS.SOIL_ANALYSIS,
        ROUTE_PATHS.ACHIEVEMENTS.WORLD_SOIL_DAY,
    ],

    // Awards Siblings
    AWARDS: [
        ROUTE_PATHS.ACHIEVEMENTS.AWARDS.KVK,
        ROUTE_PATHS.ACHIEVEMENTS.AWARDS.SCIENTIST,
        ROUTE_PATHS.ACHIEVEMENTS.AWARDS.FARMER,
    ],

    // Training & Extension Siblings
    TRAINING_EXTENSION: [
        ROUTE_PATHS.ACHIEVEMENTS.TRAININGS,
        ROUTE_PATHS.ACHIEVEMENTS.EXTENSION_ACTIVITIES,
        ROUTE_PATHS.ACHIEVEMENTS.OTHER_EXTENSION,
        ROUTE_PATHS.ACHIEVEMENTS.TECHNOLOGY_WEEK,
        ROUTE_PATHS.ACHIEVEMENTS.CELEBRATION_DAYS,
    ],
} as const;
