/**
 * Route Sibling Groups
 *
 * Centralized sibling route groups for tab navigation.
 * These groups define which routes should appear as tabs together.
 *
 * Usage:
 *   import { ROUTE_SIBLING_GROUPS } from '@/config/routeSiblingGroups'
 *   siblings: ROUTE_SIBLING_GROUPS.FLD
 */

import { ROUTE_PATHS } from '../constants/routePaths'
import { ENTITY_PATHS } from '../constants/entityConstants'

export const ROUTE_SIBLING_GROUPS = {
    // OFT Siblings — OFT is its own card on the Achievements page; the only
    // sibling tab is itself.
    OFT: [
        ROUTE_PATHS.ACHIEVEMENTS.OFT,
    ] as const,

    // FLD Siblings — three FLD-related pages grouped under the FLD card.
    FLD: [
        ROUTE_PATHS.ACHIEVEMENTS.FLD.BASE,
        ROUTE_PATHS.ACHIEVEMENTS.FLD.EXTENSION_TRAINING,
        ROUTE_PATHS.ACHIEVEMENTS.FLD.TECHNICAL_FEEDBACK,
    ] as const,

    // CFLD Siblings
CFLD: [
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.CFLD.TECHNICAL_PARAMETER,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.CFLD.EXTENSION_ACTIVITY,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.CFLD.BUDGET_UTILIZATION,
    ],

    // CRA Siblings
    CRA: [
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.CRA.DETAILS,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.CRA.EXTENSION_ACTIVITY,
    ],

    // FPO Siblings
    FPO: [
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.FPO.DETAILS,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.FPO.MANAGEMENT,
    ],

    // DRMR Siblings
    DRMR: [
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.DRMR.DETAILS,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.DRMR.ACTIVITY,
    ],

    // NARI Siblings
    NARI: [
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NARI.NUTRI_SMART,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NARI.BIO_FORTIFIED,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NARI.VALUE_ADDITION,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NARI.TRAINING_PROGRAMM,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NARI.EXTENSION_ACTIVITIES,
    ],

    // ARYA Siblings
    ARYA: [
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.ARYA.CURRENT,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.ARYA.EVALUATION,
    ],

    // NICRA Base Siblings
    NICRA_BASE: [
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.BASIC_INFORMATION,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.DETAILS,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.TRAINING,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.EXTENSION_ACTIVITY,
    ],

    // NICRA Others Siblings
    NICRA_OTHERS: [
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.OTHERS.INTERVENTION,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.OTHERS.REVENUE_GENERATED,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.OTHERS.CUSTOM_HIRING,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.OTHERS.VCRMC,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.OTHERS.SOIL_HEALTH_CARD,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.OTHERS.CONVERGENCE_PROGRAMME,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.OTHERS.DIGNITARIES_VISITED,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NICRA.OTHERS.PI_COPI_LIST,
    ],

    // Natural Farming Siblings
    NATURAL_FARMING: [
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NATURAL_FARMING.GEOGRAPHICAL_INFORMATION,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NATURAL_FARMING.PHYSICAL_INFORMATION,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NATURAL_FARMING.DEMONSTRATION_INFORMATION,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NATURAL_FARMING.FARMERS_PRACTICING,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NATURAL_FARMING.BENEFICIARIES,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NATURAL_FARMING.SOIL_DATA,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.NATURAL_FARMING.BUDGET_EXPENDITURE,
    ],

    // Agri-Drone Siblings
    AGRI_DRONE: [
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.AGRI_DRONE,
        ROUTE_PATHS.ACHIEVEMENTS.PROJECTS.DEMONSTRATION_DETAILS,
    ],

    // KVK View Siblings
    KVK_VIEW: [
        ROUTE_PATHS.ABOUT_KVK.VIEW_KVKS.DETAILS,
        ROUTE_PATHS.ABOUT_KVK.VIEW_KVKS.BANK,
        ROUTE_PATHS.ABOUT_KVK.VIEW_KVKS.EMPLOYEES,
        ROUTE_PATHS.ABOUT_KVK.VIEW_KVKS.VEHICLES,
        ROUTE_PATHS.ABOUT_KVK.VIEW_KVKS.EQUIPMENTS,
    ],

    // Soil Water Testing Siblings — World Soil Day moved to the Meetings tab.
    SOIL_WATER_TESTING: [
        ROUTE_PATHS.ACHIEVEMENTS.SOIL_ANALYSIS,
    ],

    // Awards Siblings
    AWARDS: [
        ROUTE_PATHS.ACHIEVEMENTS.AWARDS.KVK,
        ROUTE_PATHS.ACHIEVEMENTS.AWARDS.SCIENTIST,
        ROUTE_PATHS.ACHIEVEMENTS.AWARDS.FARMER,
    ],

    // Training Siblings — Trainings is its own card; only sibling is itself.
    TRAINING: [
        ROUTE_PATHS.ACHIEVEMENTS.TRAININGS,
    ],

    // Extension Siblings — Extension Activities + Other Extension Activities
    // grouped under the Extension card.
    EXTENSION: [
        ROUTE_PATHS.ACHIEVEMENTS.EXTENSION_ACTIVITIES,
        ROUTE_PATHS.ACHIEVEMENTS.OTHER_EXTENSION,
    ],

    // Performance Indicator - Impact Siblings
    PERFORMANCE_IMPACT: [
        ROUTE_PATHS.PERFORMANCE.IMPACT.KVK_ACTIVITIES,
        ROUTE_PATHS.PERFORMANCE.IMPACT.ENTREPRENEURSHIP,
        ROUTE_PATHS.PERFORMANCE.IMPACT.SUCCESS_STORIES,
    ],

    // Performance Indicator - District & Village Siblings
    PERFORMANCE_DISTRICT_VILLAGE: [
        ROUTE_PATHS.PERFORMANCE.DISTRICT_VILLAGE.DISTRICT_LEVEL,
        ROUTE_PATHS.PERFORMANCE.DISTRICT_VILLAGE.OPERATIONAL_AREA,
        ROUTE_PATHS.PERFORMANCE.DISTRICT_VILLAGE.VILLAGE_ADOPTION,
        ROUTE_PATHS.PERFORMANCE.DISTRICT_VILLAGE.PRIORITY_THRUST,
    ],

    // Performance Indicator - Infrastructure Siblings
    PERFORMANCE_INFRASTRUCTURE: [
        ROUTE_PATHS.PERFORMANCE.INFRASTRUCTURE.DEMONSTRATION_UNITS,
        ROUTE_PATHS.PERFORMANCE.INFRASTRUCTURE.INSTRUCTIONAL_FARM_CROPS,
        ROUTE_PATHS.PERFORMANCE.INFRASTRUCTURE.PRODUCTION_UNITS,
        ROUTE_PATHS.PERFORMANCE.INFRASTRUCTURE.INSTRUCTIONAL_FARM_LIVESTOCK,
        ROUTE_PATHS.PERFORMANCE.INFRASTRUCTURE.HOSTEL,
        ROUTE_PATHS.PERFORMANCE.INFRASTRUCTURE.RAINWATER_HARVESTING,
    ],

    // About KVK - Infrastructure & Land Details Siblings (Staff Quarters relocated here from Performance Indicators)
    ABOUT_KVK_INFRASTRUCTURE: [
        ENTITY_PATHS.KVK_INFRASTRUCTURE,
        ENTITY_PATHS.KVK_LAND_DETAILS,
        ROUTE_PATHS.PERFORMANCE.INFRASTRUCTURE.STAFF_QUARTERS,
    ],

    // Performance Indicator - Financial Siblings
    PERFORMANCE_FINANCIAL: [
        ROUTE_PATHS.PERFORMANCE.FINANCIAL.BUDGET_DETAILS,
        ROUTE_PATHS.PERFORMANCE.FINANCIAL.PROJECT_BUDGET,
        ROUTE_PATHS.PERFORMANCE.FINANCIAL.REVOLVING_FUND,
        ROUTE_PATHS.PERFORMANCE.FINANCIAL.REVENUE_GENERATION,
        ROUTE_PATHS.PERFORMANCE.FINANCIAL.RESOURCE_GENERATION,
    ],

    // Performance Indicator - Linkages Siblings
    PERFORMANCE_LINKAGES: [
        ROUTE_PATHS.PERFORMANCE.LINKAGES.FUNCTIONAL_LINKAGE,
        ROUTE_PATHS.PERFORMANCE.LINKAGES.SPECIAL_PROGRAMMES,
    ],

    // Miscellaneous - Diseases Siblings
    MISC_DISEASES: [
        ROUTE_PATHS.MISCELLANEOUS.DISEASES.CROPS,
        ROUTE_PATHS.MISCELLANEOUS.DISEASES.LIVESTOCK,
    ],

    // Miscellaneous - PPV & FRA Siblings
    MISC_PPV_FRA: [
        ROUTE_PATHS.MISCELLANEOUS.PPV_FRA.TRAINING,
        ROUTE_PATHS.MISCELLANEOUS.PPV_FRA.PLANT_VARIETIES,
    ],

    // Digital Information Siblings
    DIGITAL_INFORMATION: [
        ROUTE_PATHS.DIGITAL_INFORMATION.MOBILE_APP,
        ROUTE_PATHS.DIGITAL_INFORMATION.WEB_PORTAL,
        ROUTE_PATHS.DIGITAL_INFORMATION.KISAN_SARATHI,
        ROUTE_PATHS.DIGITAL_INFORMATION.KISAN_MOBILE_ADVISORY,
        ROUTE_PATHS.DIGITAL_INFORMATION.OTHER_CHANNELS,
    ],

    // Swachhta Bharat Abhiyaan Siblings
    SWACHHTA_BHARAT_ABHIYAAN: [
        ROUTE_PATHS.SWACHHTA_BHARAT_ABHIYAAN.SEWA,
        ROUTE_PATHS.SWACHHTA_BHARAT_ABHIYAAN.PAKHWADA,
        ROUTE_PATHS.SWACHHTA_BHARAT_ABHIYAAN.BUDGET,
    ],

    MEETINGS: [
        ROUTE_PATHS.MEETINGS.SAC,
        ROUTE_PATHS.MEETINGS.OTHER,
    ],

    SPECIAL_DAYS: [
        ROUTE_PATHS.ACHIEVEMENTS.TECHNOLOGY_WEEK,
        ROUTE_PATHS.ACHIEVEMENTS.CELEBRATION_DAYS,
        ROUTE_PATHS.ACHIEVEMENTS.WORLD_SOIL_DAY,
        ROUTE_PATHS.ACHIEVEMENTS.POSHAN_MAHA,
    ],
} as const;
