function esc(t){if(t===null||t===undefined)return'';const m={'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'};return String(t).replace(/[&<>"']/g,c=>m[c]);}
function n(v){const x=Number(v);return Number.isFinite(x)?x:0;}

function pickFirst(...values){
  for (const value of values) {
    if (value !== null && value !== undefined && value !== '') return value;
  }
  return '';
}

function resolveStateName(row){
  return pickFirst(
    row?.stateName,
    row?.state,
    row?.kvk?.stateName,
    row?.kvk?.state?.stateName,
    row?.kvks?.stateName,
    row?.kvks?.state?.stateName
  );
}

function resolveKvkName(row){
  return pickFirst(
    row?.kvkName,
    row?.kvk?.kvkName,
    row?.kvks?.kvkName
  );
}

function renderNicraFarmImplementSection(section, data, sectionId, isFirstSection){
  const rows = Array.isArray(data)?data:(data?[data]:[]);
  if(rows.length===0){ return this._generateEmptySection(section,null,sectionId,isFirstSection); }
  const body = rows.map((r,idx)=>`
    <tr>
      <td>${idx+1}</td>
      <td class="l">${esc(resolveStateName(r))}</td>
      <td class="l">${esc(resolveKvkName(r))}</td>
      <td class="l">${esc(r.nameOfFarmImplement || '')}</td>
      <td>${n(r.genM)}</td><td>${n(r.genF)}</td><td>${n(r.genT)}</td>
      <td>${n(r.obcM)}</td><td>${n(r.obcF)}</td><td>${n(r.obcT)}</td>
      <td>${n(r.scM)}</td><td>${n(r.scF)}</td><td>${n(r.scT)}</td>
      <td>${n(r.stM)}</td><td>${n(r.stF)}</td><td>${n(r.stT)}</td>
      <td>${n(r.totM)}</td><td>${n(r.totF)}</td><td>${n(r.totT)}</td>
      <td>${n(r.areaCovered)}</td>
      <td>${n(r.farmImplementUsedHours)}</td>
      <td>${n(r.revenueGeneratedRs)}</td>
      <td>${n(r.expenditureIncurredRepairingRs)}</td>
    </tr>
  `).join('');

  return `
<div id="${sectionId}" class="${isFirstSection?'section-page section-page-first':'section-page section-page-continued'}">
  <style>
    .nicra-fi { width:100%; table-layout:fixed; border-collapse:collapse; font-size:6.2pt; line-height:1.15; }
    .nicra-fi th,.nicra-fi td { border:0.2px solid #000; padding:2px 3px; text-align:center; vertical-align:middle; word-break:break-word; }
    .nicra-fi thead th { background:#fff; font-weight:bold; }
    .nicra-fi .l { text-align:left; }
  </style>
  <h1 class="section-title">${section.id} ${this._escapeHtml(section.title)}</h1>
  <table class="nicra-fi">
    <thead>
      <tr>
        <th rowspan="2">S.No.</th>
        <th rowspan="2">State</th>
        <th rowspan="2">KVK</th>
        <th rowspan="2">Name of farm implement/equipment</th>
        <th colspan="3">General</th>
        <th colspan="3">OBC</th>
        <th colspan="3">SC</th>
        <th colspan="3">ST</th>
        <th colspan="3">Total</th>
        <th rowspan="2">Area covered by Farm Implement</th>
        <th rowspan="2">Farm Implement used (In Hours)</th>
        <th rowspan="2">Revenue generated by Farm Implement (Rs.)</th>
        <th rowspan="2">Expenditure incurred on repairing (Rs.)</th>
      </tr>
      <tr>
        <th>M</th><th>F</th><th>T</th>
        <th>M</th><th>F</th><th>T</th>
        <th>M</th><th>F</th><th>T</th>
        <th>M</th><th>F</th><th>T</th>
        <th>M</th><th>F</th><th>T</th>
      </tr>
    </thead>
    <tbody>
      ${body}
    </tbody>
  </table>
</div>`;
}

module.exports = { renderNicraFarmImplementSection };
